### PR TITLE
Checking if bp is treated as a frame ptr in given function (fix #12867)

### LINKED ISSUE #12867: arguments identification: rbp may be used to store values
Some functions do not need to use `rbp` to store the stack base pointer, but they may use the register as a general purpose register. radare2 does not understand it and identifies all accesses from `rbp` as arguments.

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64, Ubuntu x86 32
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 22394 @ linux-x86-64 git.3.2.1-124-ge830306ff
commit: e830306ff0eee218213102499096fbc531dfb277 build: 2019-01-20__16:27:25

### Expected behavior
```
> afv
var int local_8h @ rsp+0x8
var int local_10h @ rsp+0x10
var int local_18h @ rsp+0x18
arg int arg1 @ rdi
arg int arg2 @ rsi
```

### Actual behavior
```
> afv
var int local_8h @ rsp+0x8
var int local_10h @ rsp+0x10
var int local_18h @ rsp+0x18
arg int arg_8h @ rbp+0x8
arg int arg_10h @ rbp+0x10
arg int arg1 @ rdi
arg int arg2 @ rsi
```

### Steps to reproduce the behavior 
```
$ radare2 -
> wx f30f1efa4157415641554989fdbf18000000415455534889f34883ec2864488b042528000000488944241831c0e8de4dffff4889c5488b431048c74508000000004889450031c0e8c453ffff488b0dcd48010031d231f64889c74889442410e87c5bffff488b7c241031d24889eee8ad4affff488b7c2410488b1f4885db0f842b0100000f1f40004889dee8b04effff4c8b73084889df4d8b26e8e150ffffc64510004d8b24244d85e40f84dd000000bf18000000e8564dffff4889c5498b442408488b401048894500498b442408498b5e08488b384885db0f8449010000e8bc50ffff4889df4989c7e8b150ffff498d7c0701e8174dffff488945084d8b7e084889c34c89ffe89450ffff4c89fe4889df4889c2e8965cffff498b442408488b304889f74889742408e87150ffff498b7e084989c7e86550ffff488b742408498d5701488d3c03e8635cffff498b442408488b5018488b5a104885db0f857d000000488b4010488338000f849a000000488b7c241031d24889eee8a049ffff4d8b24244d85e40f8523ffffff498b7e08e8ea4fffff4c89f7e8e24fffff488b7c2410488b1f4885db0f85d9feffff488d7c2410e8a757ffff488b4424186448330425280000000f85940000004883c4285b5d415c415d415e415fc30f1f4000488b13488b75084c89efe8a14bffff488b5b084885db75e8498b442408488b4010488338000f8566ffffff488b7d08e86c4fffff4889efe8644fffffe982feffff0f1f8000000000e8734fffff488d7801e8da4bffff488945084889c3498b4424084c8b384c89ffe8534fffff4c89fe4889df488d5001e8545bffffe9ecfeffffe8aa55ffff
> af
> afv
```

### Additional Logs, screenshots, source-code,  configuration dump, ...
```
0x00000012                 4154  push r12
0x00000014                   55  push rbp                   <- RBP is saved
0x00000015                   53  push rbx
0x00000016               4889f3  mov rbx, rsi
0x00000019             4883ec28  sub rsp, 0x28
0x0000001d   64488b042528000000  mov rax, qword fs:[0x28]
0x00000026           4889442418  mov qword [rsp + 0x18], rax
0x0000002b                 31c0  xor eax, eax
0x0000002d           e8de4dffff  call 0xffffffffffff4e10
0x00000032               4889c5  mov rbp, rax               <- RBP is used to store the result of the previous function (which was a malloc)
0x00000035             488b4310  mov rax, qword [rbx + 0x10]
0x00000039     48c7450800000000  mov qword [arg_8h], 0     <- this should be "rbp + 8", not arg_8h because this is actually setting the memory allocated before
0x00000041             48894500  mov qword [rbp], rax     <- same here
0x00000045                 31c0  xor eax, eax
```

### PR DESCRIPTION
**Pull request by bart1e**
Not sure how it will work on non-x86 architectures (I don't know how frame ptr is handled there). Any suggestions how to improve it are welcome.

### CODE REVIEW

File: libr/anal/fcn.c [hunk 1]
```diff
@@ -1181,7 +1184,7 @@ static int fcn_recurse(RAnal *anal, RAnalFunction *fcn, ut64 addr, ut64 len, int
 			// swapped parameters wtf
 			r_anal_xrefs_set (anal, op.addr, op.ptr, R_ANAL_REF_TYPE_DATA);
 		}
-
+
```
Comment (radare) [inline libr/anal/fcn.c]: remove this

File: libr/anal/fcn.c [hunk 2]
```diff
@@ -1207,6 +1210,7 @@ static int fcn_recurse(RAnal *anal, RAnalFunction *fcn, ut64 addr, ut64 len, int
 					return R_ANAL_RET_END;
 				}
 			}
+
```
Comment (radare) [inline libr/anal/fcn.c]: and this

File: libr/anal/fcn.c [hunk 3]
```diff
@@ -2462,3 +2465,84 @@ R_API bool r_anal_fcn_get_purity(RAnal *anal, RAnalFunction *fcn) {
...
+		RAnalOp op;
+		ut64 at, end = bb->addr + bb->size;
+		ut8 *buf = malloc (bb->size);
+		if (!buf) {
+			continue;
+		}
+		(void)anal->iob.read_at (anal->iob.io, bb->addr, (ut8 *) buf, bb->size);
+		int idx = 0;
+		for (at = bb->addr; at < end;) {
+			memset (&op, 0, sizeof (op));
```
Comment (radare) [inline libr/anal/fcn.c]: r_anal_op should be already initializing this struct, dont do it twice

File: libr/anal/fcn.c [hunk 4]
```diff
@@ -2462,3 +2465,84 @@ R_API bool r_anal_fcn_get_purity(RAnal *anal, RAnalFunction *fcn) {
...
+			r_anal_op (anal, &op, at, buf + idx, bb->size - idx, R_ANAL_OP_MASK_VAL | R_ANAL_OP_MASK_OPEX);
+			if (op.size < 1) {
+				op.size = 1;
+			}
+			switch (op.type) {
+			case R_ANAL_OP_TYPE_MOV:
+				if (can_affect_bp (anal, &op) && op.src[0] && op.src[0]->reg && op.src[0]->reg->name
+				&& strcmp(op.src[0]->reg->name, anal->reg->name[R_REG_NAME_SP])) {
```
Comment (radare) [inline libr/anal/fcn.c]: missing (

File: libr/core/canal.c [hunk 5]
```diff
@@ -860,6 +859,10 @@ static int core_anal_fcn(RCore *core, ut64 at, ut64 from, int reftype, int depth
 		}
 		free (next);
 	}
+	r_anal_fcn_check_bp_use(core->anal, fcn);
```
Comment (radare) [inline libr/core/canal.c]: missing space

File: libr/core/canal.c [hunk 6]
```diff
@@ -899,6 +902,10 @@ static int core_anal_fcn(RCore *core, ut64 at, ut64 from, int reftype, int depth
 			}
 		}
 	}
+	r_anal_fcn_check_bp_use(core->anal, fcn);
+	if (!fcn->rbp_as_frame_ptr) {
+		r_anal_var_delete_all(core->anal, fcn->addr, 'b');
```
Comment (radare) [inline libr/core/canal.c]: missing space

File: libr/anal/fcn.c [hunk 7]
```diff
@@ -50,6 +50,8 @@ typedef struct fcn_tree_iter_t {
 static Sdb *HB = NULL;
 #endif
 
+
```
Comment (radare) [inline libr/anal/fcn.c]: empty lines

**Comment by radare** [comment]
also is red because of travis, but ill fix asap, so rebase when master is green

**Comment by bart1e** [comment]
OK, thank you for your comments. I'll do it.

**Comment by bart1e** [comment]
> this code is x86-specific and we shouldnt run it outside x86 analysis, can u add some ifs here an there for this?

Is there any variable / macro for checking architecture?

File: libr/core/canal.c [hunk 8]
```diff
@@ -860,6 +859,12 @@ static int core_anal_fcn(RCore *core, ut64 at, ut64 from, int reftype, int depth
 		}
 		free (next);
 	}
+	if (!strcmp (R_SYS_ARCH, "x86")) {
```
Comment (radare) [inline libr/core/canal.c]: thats not correct, you should do: !strcmp(core->anal->cur->arch, "x86") (check if core->anal->cur is non null before doing it)

**Comment by radare** [comment]
please rebase, master is green now

**Comment by radare** [comment]
Looks red

**Comment by bart1e** [comment]
I'll fix that today.

File: libr/anal/fcn.c [hunk 9]
```diff
@@ -386,6 +386,7 @@ R_API RAnalFunction *r_anal_fcn_new() {
 	fcn->fingerprint = NULL;
 	fcn->diff = r_anal_diff_new ();
 	fcn->has_changed = true;
+	fcn->rbp_as_frame_ptr = true;
```
Comment (radare) [inline libr/anal/fcn.c]: RAnalFunction is an arch that shouldnt hold arch-specific stuff, what im worried about this PR iss that is introducing some x86-specific naming in here. I bet this issue can be replicated on other archs, so i would probably use a different naming for this variable. and in fact im thinking in adding attribute binary mask field in there to hold info like this:

fcn->attributes = (BPFRAME | NORETURN | INLINE | UNUSED | ...)

can you rename this variable tp bpframe? instead of "rbp_as_frame_ptr" ? we will think about having this extended attribuet field later

Comment (bart1e) [reply libr/anal/fcn.c]: Thank you for your comment. I changed it. I was also thinking about moving can_affect_bp function to op.c.
