### PR TITLE
bin: fix void* != ut64 in elf parser

### LINKED ISSUE #9593: void* != ut64 in elf parser
```
c38f140c67 (Riccardo Schirone       2018-02-22 00:11:26 +0100  856) static bool ht_insert_intu64(SdbHash* ht, int key, ut64 value) {
c38f140c67 (Riccardo Schirone       2018-02-22 00:11:26 +0100  857)     return ht_insert (ht, sdb_fmt (-1, "%d", key), (void *)value);
c38f140c67 (Riccardo Schirone       2018-02-22 00:11:26 +0100  858) }
c38f140c67 (Riccardo Schirone       2018-02-22 00:11:26 +0100  859)
c38f140c67 (Riccardo Schirone       2018-02-22 00:11:26 +0100  860) static ut64 ht_find_intu64(SdbHash* ht, int key, bool* found) {
c38f140c67 (Riccardo Schirone       2018-02-22 00:11:26 +0100  861)     return (ut64)ht_find (ht, sdb_fmt (-1, "%d", key), found);
c38f140c67 (Riccardo Schirone       2018-02-22 00:11:26 +0100  862) }
```

### PR DESCRIPTION
**Pull request by ret2libc**
fix #9593

### CODE REVIEW

File: libr/bin/p/bin_elf.c [hunk 1]
```diff
@@ -881,11 +881,19 @@ static void _patch_reloc (ut16 e_machine, RIOBind *iob, RBinElfReloc *rel, ut64
 }
 
 static bool ht_insert_intu64(SdbHash* ht, int key, ut64 value) {
-	return ht_insert (ht, sdb_fmt (-1, "%d", key), (void *)value);
+	ut64 *mvalue = malloc(sizeof(ut64));
```
Comment (radare) [inline libr/bin/p/bin_elf.c]: missing space before each (

Comment (radare) [reply libr/bin/p/bin_elf.c]: also null deref in here

Comment (radare) [reply libr/bin/p/bin_elf.c]: also, why not use dict, and avoid converting numbers to strings and allocating them in heap?

File: libr/bin/p/bin_elf.c [hunk 2]
```diff
@@ -881,11 +881,19 @@ static void _patch_reloc (ut16 e_machine, RIOBind *iob, RBinElfReloc *rel, ut64
...
 }
 
 static ut64 ht_find_intu64(SdbHash* ht, int key, bool* found) {
-	return (ut64)ht_find (ht, sdb_fmt (-1, "%d", key), found);
+	ut64 *mvalue = (ut64 *)ht_find (ht, sdb_fmt (-1, "%d", key), found);
+	return *mvalue;
+}
+
+static void relocs_by_sym_free(HtKv *kv) {
+	free(kv->key);
```
Comment (radare) [inline libr/bin/p/bin_elf.c]: missing space before (

File: libr/bin/p/bin_elf.c (hunk 1 above)
Comment (ret2libc) [reply libr/bin/p/bin_elf.c]: i'm not using dict because I think it's a bad implementation of an hash table :) so I prefer to keep using ht.

File: libr/bin/p/bin_elf.c [hunk 3]
```diff
@@ -881,11 +881,24 @@ static void _patch_reloc (ut16 e_machine, RIOBind *iob, RBinElfReloc *rel, ut64
...
+	}
+
+	*mvalue = value;
+	return ht_insert (ht, sdb_fmt (-1, "%d", key), (void *)mvalue);
 }
 
 static ut64 ht_find_intu64(SdbHash* ht, int key, bool* found) {
-	return (ut64)ht_find (ht, sdb_fmt (-1, "%d", key), found);
+	ut64 *mvalue = (ut64 *)ht_find (ht, sdb_fmt (-1, "%d", key), found);
+	assert (mvalue != NULL);
```
Comment (radare) [inline libr/bin/p/bin_elf.c]: dont use asserts, just return ut64_MAX
