### PR TITLE
Fixes #10903: slow bins

### LINKED ISSUE #10903: Slow to analyze some crafted files
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | Mach-o, Dalvik, ELF, Java Class, mdmp, etc (according to `file`)
| Architecture/bits of the file (mandatory)            | -
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18917 @ linux-x86-64 git.2.7.0-236-ge6796bf81 commit: e6796bf8129f614a4f3b91d1e00b79b1e9a8eaca build: 2018-08-03__11:04:57

### Expected behavior
r2 exits.

### Actual behavior
r2 takes long to analyze.

### Steps to reproduce the behavior 
- Download files from [this directory](https://github.com/ntu-sec/pocs/tree/master/radare2-18917/hangs).
- run `r2 -Q $FILE`

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by ret2libc** [comment]
This fixes most of the bins provided in the issue #10903 except the Java ones.

**Comment by ret2libc** [comment]
r2r PR: https://github.com/radare/radare2-regressions/pull/1464

File: libr/bin/p/bin_mach0.c [hunk 1]
```diff
@@ -195,7 +195,11 @@ static void process_constructors (RBinFile *bf, RList *ret, int bits) {
 			if (!buf) {
 				continue;
 			}
-			(void)r_buf_read_at (bf->buf, sec->paddr, buf, sec->size);
+			int read = r_buf_read_at (bf->buf, sec->paddr, buf, sec->size);
+			if (read < sec->size) {
+				eprintf("process_constructors: cannot process section %s\n", sec->name);
```
Comment (radare) [inline libr/bin/p/bin_mach0.c]: missing space before (
