### PR TITLE
get_pc_from_stack for computed refs

### LINKED ISSUE #6402: String(DATA) xref does not work with x86 binary built with -fPIC -m32
I found that string xref does not work  when target binary is compiled with -fPIC -m32 in x86.

sample code is ..
`#include <stdio.h>

void main()
{
        printf("Hello PIC!\n");
}`

build cmd > gcc -fPIC -m32 test.c

image

image

to make PIC code, compiler generate small code for getting PC address using "fcn.08048350"
so, ebx is set 0x0804842c after calling "fcn.08048350"
     ebx +0x1bd4 - 0x1b20 = 0x08484e0 

image

and, IDA works with this sample.

Almost data xref will not work with PIC codes in x86 32bit ELF from this reason.
is it possible to patch this issue?

### PR DESCRIPTION
**Pull request by SrimantaBarua**
Work in progress, need comments.
With some work, this would fix #6402 and #6819.
Is this the right way to go though? Or should this check be inserted in another place?

Obvious issues/ caveats with the code right now -
1) Only supports x86 / x86_64
3) Output for bins/elf/redpill is currently as below. Will look into how r2 understands these are strings.
```
$ r2 redpill
[0x00000f40]> e anal.strings = true
[0x00000f40]> aa
[0x00000f40]> aae
...
[0x00000f40]> axt 0x00001d89
data 0x00001457 lea eax, [esi - 0x2277] in main
[0x00000f40]> axt 0x00001da0
data 0x0000148e lea eax, [esi - 0x2260] in main
...
```
4) Line 3421 in canal.c and the part before that. Using this temporary solution because values pushed on stack (like PC) during ESIL emulation are not really stored...

### CODE REVIEW

**Comment by Maijin** [comment]
This is probably `asm.relsub` you're looking for

**Comment by SrimantaBarua** [comment]
@Maijin Yeah `asm.relsub` is set to `true`, but it doesn't resolve the case where the compiler inserts a tiny function which you call, to get PC on the stack, and then move that value to a register. Then `lea` from that register.
That's the case with both the issues I referred to.

**Comment by Maijin** [comment]
Yep just referring to it because that's probably where is the code to improve :)

**Comment by SrimantaBarua** [comment]
Oh okay, I'll look into it. Thanks!

File: libr/core/canal.c [hunk 1]
```diff
@@ -3500,16 +3601,16 @@ R_API void r_core_anal_esil(RCore *core, const char *str, const char *target) {
...
 			switch (op.type) {
 			case R_ANAL_OP_TYPE_LEA:
 				if ((target && op.ptr == ntarget) || !target) {
 					if (core->anal->cur && strcmp (core->anal->cur->arch, "arm")) {
 						if (cfg_anal_strings) {
-							if (CHECKREF(op.ptr)) {
-								r_anal_ref_add (core->anal, op.ptr, cur, 'd');
-								if ((target && op.ptr == ntarget) || !target) {
-									add_string_ref (core, op.ptr);
+							if (CHECKREF(ESIL->cur)) {
```
Comment (radare) [inline libr/core/canal.c]: missing space before (

File: libr/core/canal.c [hunk 2]
```diff
@@ -3596,6 +3697,8 @@ R_API void r_core_anal_esil(RCore *core, const char *str, const char *target) {
 						if (myvalid (core->io, dst)) {
 							r_anal_ref_add (core->anal, dst, cur, 'C');
 						}
+						ESIL->old = cur + op.size;
+						getpcfromstack_x86(core, ESIL);
```
Comment (radare) [inline libr/core/canal.c]: missing space before (

Comment (radare) [inline libr/core/canal.c]: this is executed on non-x86 target too. which may be wrong.

**Comment by radare** [comment]
can you provide a test case for this?

**Comment by radare** [comment]
yes i think aae/asmemu is the right place for this, but esil is platform agnostic, so that should be arch-independent. maybe we can find a similar case for arm/mips and test it there

**Comment by SrimantaBarua** [comment]
@radare arm/mips have a link register which stores return address for function calls, so they don't use this. But yeah, this should be more arch-independent, I just don't know which architectures could use this. Will need to read up.

Also, WIP, don't merge yet. I need to look at how to make radare recognize that the data refs that are generated are to strings, so that it can be shown in `pdf` or `axt`.

**Comment by radare** [comment]
Theres a function that given an address tells you the type of data. Use this to detect the kind of contents to resolve strings or so.

**Comment by radare** [comment]
We can strstr for x86 for now. But may be good to confirm that this code is causing no side effects to other archs so would be generic too

**Comment by SrimantaBarua** [comment]
Added test for this: https://github.com/radare/radare2-regressions/pull/735

**Comment by Maijin** [comment]
Tests are wrong. You should leave the current test as they are. And copy/paste them with relsub disabled.

**Comment by SrimantaBarua** [comment]
@Maijin okay, I'll do that. A question though.. I know IDA shows `lea eax, str.Hello_PIC_`, but the instruction is technically doing a `lea eax, [ebx - 0x1b20]`, not loading the address of `str.Hello_PIC_` as an immediate value. So is better to show `lea eax, str.Hello_PIC_` or `lea eax, [ebx - 0x1b20]`?

**Comment by Maijin** [comment]
str.hello when relsub is enabled 
[XXX] when relsub disabled.

**Comment by Maijin** [comment]
Also if tests now pass, remove the 1 in BROKEN=1

**Comment by SrimantaBarua** [comment]
Okay, done

**Comment by radare** [comment]
lgtm

**Comment by Maijin** [comment]
Well next time, you could merge r2r before https://github.com/radare/radare2-regressions/pull/735 :(
