### PR TITLE
 Do not create new RCore in get_hash_debug_file(), Fixes #10447

### LINKED ISSUE #10447: `dmh` faults when debugging a 32 bit binary on a 64 linux platform
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x86 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.7.0-git 18517 @ linux-x86-64 git.2.6.0-332-g9620ffa commit: 9620ffab1607219f11a151aea32b9a15a43c97fd build: 2018-06-22__11:09:34

### Expected behavior

Display heap when using `dmh`

### Actual behavior

`dmh` crashes when debugging a 32 bit binary on a 64 linux platform (it works correctly with 64 bit binaries). 

### Steps to reproduce the behavior 

The program:

```c
#include <stdlib.h>

int main() {
	char *a = malloc(100);
	return 0;
}
```

compile on 32 bits:

	$ gcc -m32 -o foo foo.c

and then it crashes:

```
$ r2 -d foo 
Process with PID 23589 started...
= attach 23589 23589
bin.baddr 0x08048000
Using 0x8048000
asm.bits 32
 -- nothing personal, just bitness
[0x08048310]> pd 17 @ sym.main
            ;-- main:
            0x0804840b      8d4c2404       lea ecx, [esp + 4]          ; 4
            0x0804840f      83e4f0         and esp, 0xfffffff0
            0x08048412      ff71fc         push dword [ecx - 4]
            0x08048415      55             push ebp
            0x08048416      89e5           mov ebp, esp
            0x08048418      51             push ecx
            0x08048419      83ec14         sub esp, 0x14
            0x0804841c      83ec0c         sub esp, 0xc
            0x0804841f      6a64           push 0x64                   ; 'd' ; 100
            0x08048421      e8bafeffff     call sym.imp.malloc
            0x08048426      83c410         add esp, 0x10
            0x08048429      8945f4         mov dword [ebp - 0xc], eax
            0x0804842c      b800000000     mov eax, 0
            0x08048431      8b4dfc         mov ecx, dword [ebp - 4]
            0x08048434      c9             leave
            0x08048435      8d61fc         lea esp, [ecx - 4]
            0x08048438      c3             ret
[0x08048310]> dcu 0x08048426
Continue until 0x08048426 using 1 bpsize
hit breakpoint at: 8048426
[0x08048426]> dmh
Warning: glibc library with symbol main_arena could not be found. Is libc6-dbg installed?
=================================================================
==23588==ERROR: AddressSanitizer: heap-use-after-free on address 0x7fdb1de81fa0 at pc 0x7fdb29bd0fe5 bp 0x7fff2a4816f0 sp 0x7fff2a4816e0
READ of size 8 at 0x7fdb1de81fa0 thread T0
    #0 0x7fdb29bd0fe4 in r_core_task_self /home/user/src/radare2/libr/core/task.c:329
    #1 0x7fdb2998b57b in r_core_break /home/user/src/radare2/libr/core/core.c:1782
    #2 0x7fdb290fdf67 in r_cons_is_breaked /home/user/src/radare2/libr/cons/cons.c:246
    #3 0x7fdb29aae493 in cmd_interpret /home/user/src/radare2/libr/core/cmd.c:931
    #4 0x7fdb29b55554 in r_cmd_call /home/user/src/radare2/libr/core/cmd_api.c:237
    #5 0x7fdb29ab93f1 in r_core_cmd_subst_i /home/user/src/radare2/libr/core/cmd.c:2694
    #6 0x7fdb29ab25db in r_core_cmd_subst /home/user/src/radare2/libr/core/cmd.c:1723
    #7 0x7fdb29abe6fd in r_core_cmd /home/user/src/radare2/libr/core/cmd.c:3389
    #8 0x7fdb2998f42e in set_prompt /home/user/src/radare2/libr/core/core.c:2153
    #9 0x7fdb2998fc2b in r_core_prompt /home/user/src/radare2/libr/core/core.c:2212
    #10 0x562b0eb2984b in main /home/user/src/radare2/binr/radare2/radare2.c:1363
    #11 0x7fdb23dca82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #12 0x562b0eb22f48 in _start (/home/user/src/radare2/binr/radare2/radare2+0x6f48)

0x7fdb1de81fa0 is located 399264 bytes inside of 399392-byte region [0x7fdb1de20800,0x7fdb1de82020)
freed by thread T0 here:
    #0 0x7fdb2a05b2ca in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x982ca)
    #1 0x7fdb2998eb6c in r_core_free /home/user/src/radare2/libr/core/core.c:2072
    #2 0x7fdb299a592d in get_hash_debug_file /home/user/src/radare2/libr/core/cmd_debug.c:1430
    #3 0x7fdb299aae13 in r_resolve_symbol_32 /home/user/src/radare2/libr/core/linux_heap_glibc.c:273
    #4 0x7fdb299ab2cd in r_resolve_main_arena_32 /home/user/src/radare2/libr/core/linux_heap_glibc.c:321
    #5 0x7fdb299b2fb0 in cmd_dbg_map_heap_glibc_32 /home/user/src/radare2/libr/core/linux_heap_glibc.c:1307
    #6 0x7fdb299a6199 in r_debug_heap /home/user/src/radare2/libr/core/cmd_debug.c:1487
    #7 0x7fdb299a8a70 in cmd_debug_map /home/user/src/radare2/libr/core/cmd_debug.c:1837
    #8 0x7fdb299d4de1 in cmd_debug /home/user/src/radare2/libr/core/cmd_debug.c:4522
    #9 0x7fdb29b55554 in r_cmd_call /home/user/src/radare2/libr/core/cmd_api.c:237
    #10 0x7fdb29ab93f1 in r_core_cmd_subst_i /home/user/src/radare2/libr/core/cmd.c:2694
    #11 0x7fdb29ab25db in r_core_cmd_subst /home/user/src/radare2/libr/core/cmd.c:1723
    #12 0x7fdb29abe6fd in r_core_cmd /home/user/src/radare2/libr/core/cmd.c:3389
    #13 0x7fdb2998fe35 in r_core_prompt_exec /home/user/src/radare2/libr/core/core.c:2230
    #14 0x562b0eb298b4 in main /home/user/src/radare2/binr/radare2/radare2.c:1371
    #15 0x7fdb23dca82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

previously allocated by thread T0 here:
    #0 0x7fdb2a05b79a in __interceptor_calloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x9879a)
    #1 0x7fdb2997fc86 in r_core_new /home/user/src/radare2/libr/core/core.c:705
    #2 0x7fdb299a54ec in get_hash_debug_file /home/user/src/radare2/libr/core/cmd_debug.c:1397
    #3 0x7fdb299aae13 in r_resolve_symbol_32 /home/user/src/radare2/libr/core/linux_heap_glibc.c:273
    #4 0x7fdb299ab2cd in r_resolve_main_arena_32 /home/user/src/radare2/libr/core/linux_heap_glibc.c:321
    #5 0x7fdb299b2fb0 in cmd_dbg_map_heap_glibc_32 /home/user/src/radare2/libr/core/linux_heap_glibc.c:1307
    #6 0x7fdb299a6199 in r_debug_heap /home/user/src/radare2/libr/core/cmd_debug.c:1487
    #7 0x7fdb299a8a70 in cmd_debug_map /home/user/src/radare2/libr/core/cmd_debug.c:1837
    #8 0x7fdb299d4de1 in cmd_debug /home/user/src/radare2/libr/core/cmd_debug.c:4522
    #9 0x7fdb29b55554 in r_cmd_call /home/user/src/radare2/libr/core/cmd_api.c:237
    #10 0x7fdb29ab93f1 in r_core_cmd_subst_i /home/user/src/radare2/libr/core/cmd.c:2694
    #11 0x7fdb29ab25db in r_core_cmd_subst /home/user/src/radare2/libr/core/cmd.c:1723
    #12 0x7fdb29abe6fd in r_core_cmd /home/user/src/radare2/libr/core/cmd.c:3389
    #13 0x7fdb2998fe35 in r_core_prompt_exec /home/user/src/radare2/libr/core/core.c:2230
    #14 0x562b0eb298b4 in main /home/user/src/radare2/binr/radare2/radare2.c:1371
    #15 0x7fdb23dca82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: heap-use-after-free /home/user/src/radare2/libr/core/task.c:329 r_core_task_self
Shadow bytes around the buggy address:
  0x0ffbe3bc83a0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0ffbe3bc83b0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0ffbe3bc83c0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0ffbe3bc83d0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0ffbe3bc83e0: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0ffbe3bc83f0: fd fd fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd
  0x0ffbe3bc8400: fd fd fd fd fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffbe3bc8410: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffbe3bc8420: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffbe3bc8430: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0ffbe3bc8440: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
==23588==ABORTING
```

### PR DESCRIPTION
**Pull request by thestr4ng3r**
Fixes #10447

### CODE REVIEW

File: libr/core/cmd_debug.c [hunk 1]
```diff
@@ -1406,18 +1406,25 @@ static int cmd_dbg_map_heap_glibc_32 (RCore *core, const char *input);
...
+	RBin *bin = NULL;
+	RIO *io = NULL;
 	RBinOptions *bo = NULL;
+	RListIter *iter;
 	char buf[20] = R_EMPTY;
 	int offset, err, i, j = 0;
 
-	if (!core) {
-		return;
+	bin = r_bin_new ();
```
Comment (radare) [inline libr/core/cmd_debug.c]: Define and assign in the same line

File: libr/core/cmd_debug.c [hunk 2]
```diff
@@ -1406,18 +1406,25 @@ static int cmd_dbg_map_heap_glibc_32 (RCore *core, const char *input);
...
+	if (!bin) {
+		goto out_error;
 	}
 
+	io = r_io_new ();
```
Comment (radare) [inline libr/core/cmd_debug.c]: Reuse the current io

File: libr/core/cmd_debug.c (hunk 1 above)
Comment (radare) [reply libr/core/cmd_debug.c]: Dont create new rbin instance pls
