### PR TITLE
anal: fix long vs int size issue on 32bit machines

### LINKED ISSUE #9697: radare2 command "ac" heap buffer overflow read
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Linux ubuntu 4.8.0-59-generic #64-Ubuntu SMP Thu Jun 29 19:37:59 UTC 2017 i686 i686 i686 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.5.0-git 17618 @ linux-x86-32 git.2.4.0-99-gcd5f69b commit: cd5f69b094441a664bfb38d913cb1ff599e15435 build: 2018-03-14__01:58:02

### Expected behavior

radare2 run as expected

### Actual behavior

ASAN reports a heap-buffer-overflow read vulnerability in radare2 when running "ac" command towards specified elf files.

### Steps to reproduce the behavior 

The issue can be reproduced by the following command:
`radare2 -q -c ac ./radare2-heap-buffer-overflow-read-command-ac-1.elf`
**Notice: radare2 should be build with ASAN.**

### Additional Logs, screenshots, source-code,  configuration dump, ...

ASAN reports:

```
ctf@ubuntu:~/run/test$ /home/radare2/bin/radare2 -q -c ac ./radare2-heap-buffer-overflow-read-command-ac-1.elf 
Warning: Cannot initialize strings table
Warning: Cannot initialize dynamic strings
=================================================================
==7135==ERROR: AddressSanitizer: heap-buffer-overflow on address 0xb1a00000 at pc 0xb71cc9f8 bp 0xbf8cf208 sp 0xbf8cedb8
READ of size 1 at 0xb1a00000 thread T0
    #0 0xb71cc9f7  (/usr/lib/i386-linux-gnu/libasan.so.3+0x899f7)
    #1 0xb71ce5de in __interceptor_vsnprintf (/usr/lib/i386-linux-gnu/libasan.so.3+0x8b5de)
    #2 0xb3597821 in r_strbuf_appendf /home/ctf/code/radare2/libr/util/strbuf.c:118
    #3 0xb529d4eb in v850_op /home/ctf/code/radare2/libr/../libr/anal/p/anal_v850.c:68
    #4 0xb5309513 in r_anal_op /home/ctf/code/radare2/libr/anal/op.c:101
    #5 0xb6e03dcd in r_core_anal_op /home/ctf/code/radare2/libr/core/canal.c:813
    #6 0xb6e2b0f4 in r_core_anal_cycles /home/ctf/code/radare2/libr/core/canal.c:3207
    #7 0xb6c16d55 in cmd_anal /home/ctf/code/radare2/libr/core/cmd_anal.c:6553
    #8 0xb6de6247 in r_cmd_call /home/ctf/code/radare2/libr/core/cmd_api.c:233
    #9 0xb6b31cbf in r_core_cmd_subst_i /home/ctf/code/radare2/libr/core/cmd.c:2645
    #10 0xb6b31cbf in r_core_cmd_subst /home/ctf/code/radare2/libr/core/cmd.c:1676
    #11 0xb6b390b8 in r_core_cmd /home/ctf/code/radare2/libr/core/cmd.c:3305
    #12 0xb6b5fa4d in r_core_cmd0 /home/ctf/code/radare2/libr/core/cmd.c:3472
    #13 0x8003ca7d in run_commands /home/ctf/code/radare2/binr/radare2/radare2.c:354
    #14 0x800348fd in main /home/ctf/code/radare2/binr/radare2/radare2.c:1305
    #15 0xb326f275 in __libc_start_main (/lib/i386-linux-gnu/libc.so.6+0x18275)
    #16 0x8003c572  (/home/radare2/bin/radare2+0xe572)

AddressSanitizer can not describe address in more detail (wild memory access suspected).
SUMMARY: AddressSanitizer: heap-buffer-overflow (/usr/lib/i386-linux-gnu/libasan.so.3+0x899f7) 
Shadow bytes around the buggy address:
  0x3633ffb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3633ffc0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3633ffd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3633ffe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x3633fff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x36340000:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x36340010: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x36340020: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x36340030: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x36340040: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x36340050: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Heap right redzone:      fb
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack partial redzone:   f4
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==7135==ABORTING
```

Drag and drop zip archives containing the Additional info here, don't use external services or link.
[radare2-heap-buffer-overflow-read-command-ac-1.zip](https://github.com/radare/radare2/files/1813832/radare2-heap-buffer-overflow-read-command-ac-1.zip)

### PR DESCRIPTION
**Pull request by ret2libc**
The %lld format expects a long long, but an int was provided on the
stack, so the snprintf was accessing a wrong memory to print %s. Convert
the first argument to long long to solve the issue.

Fixes #9697

### CODE REVIEW

File: libr/anal/p/anal_v850.c [hunk 1]
```diff
@@ -65,7 +65,7 @@ static int v850_op(RAnal *anal, RAnalOp *op, ut64 addr, const ut8 *buf, int len)
 		if (opcode != V850_MOV_IMM5) { // Format I
 			r_strbuf_appendf (&op->esil, "%s,%s,=", F1_RN1(word1), F1_RN2(word1));
 		} else { // Format II
-			r_strbuf_appendf (&op->esil, "%"PFMT64d",%s,=", F2_IMM(word1), F2_RN2(word1));
+			r_strbuf_appendf (&op->esil, "%"PFMT64d",%s,=", (long long)(F2_IMM(word1)), F2_RN2(word1));
```
Comment (radare) [inline libr/anal/p/anal_v850.c]: why not ut64 or st64? is this suposed to be signed?

Comment (ret2libc) [reply libr/anal/p/anal_v850.c]: yes i can use st64 sorry

**Comment by radare** [comment]
thanks
