### PR TITLE
Fix #9512, restore asm.emu in pds

### LINKED ISSUE #9512: asm.emu being enabled when using O in VV but never disabled
Make sure you are testing using the latest git version of radare2 before submitting any issue.

*If you would like to report a bug, please fill the template bellow*

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | `Ubuntu 17.10 (artful) x86/64`
| File format of the file you reverse (mandatory)      | `ELF`
| Architecture/bits of the file (mandatory)            | `x86/64`
| r2 -v full output, **not truncated** (mandatory)     | `radare2 2.4.0-git 17401 @ linux-x86-64 git.2.2.0-590-g2f76b3376 commit: 2f76b33769db26057b2e79a205dce9aef0e4a53a build: 2018-02-25__19:32:20`
### Expected behavior
Set `asm.emu` to `false` once to layout is changed. (see information bellow)

### Actual behavior
In visual mode (`VV`) when using `O` (`shift+o`) in one of the layouts `asm.emu` is set to `true` but in the following layouts it is never changed back to `false` again.

### Steps to reproduce the behavior 
  * `r2 file`
  * (go to a function)
  * `VV`
  * `O` (`shift+o`) multiple times

### Additional Logs, screenshots, source-code,  configuration dump, ...
I can fix the issue if someone points me to the actual files/methods responsible for the `O` command. Thanks :)

### PR DESCRIPTION
**Pull request by sivaramaaa**
1) The main problem was lying with asm.emu.str config var 

**Enabling asm.emu.str , also enabled asm.emu** (which is expected) : 
```
[0x100001058]> e asm.emu.str = true
[0x100001058]> e asm.emu.str
true
[0x100001058]> e asm.emu
true
```
**Disabling it , didin't restore asm.emu** : 
```
[0x100001058]> e asm.emu.str = false
[0x100001058]> e asm.emu.str
false
[0x100001058]> e asm.emu
false
```
2) The "O" command in graph was only supposed to toggle  asm.esil and asm.pseudo , but it was also toggling between summary mode (which in turn uses pds that uses asm.emu.str) , now i have remove that !!

### CODE REVIEW

File: libr/core/graph.c [hunk 1]
```diff
@@ -3571,6 +3571,8 @@ static void rotateColor(RCore *core) {
 R_API int r_core_visual_graph(RCore *core, RAGraph *g, RAnalFunction *_fcn, int is_interactive) {
 	int o_asmqjmps_letter = core->is_asmqjmps_letter;
 	int o_scrinteractive = r_config_get_i (core->config, "scr.interactive");
+	bool asm_pseudo = r_config_get_i (core->config, "asm.pseudo");
```
Comment (ret2libc) [inline libr/core/graph.c]: see if you can use RConfigHold instead of the usual save/set/restore which is more error prone. It should be enough to call either `r_config_save_num` or `r_config_save_char` and r_config_restore at the end of this function should do everything else.

File: libr/core/graph.c [hunk 2]
```diff
@@ -3902,15 +3904,10 @@ R_API int r_core_visual_graph(RCore *core, RAGraph *g, RAnalFunction *_fcn, int
 			break;
 		case 'O':
 			disMode++;
-			if (disMode > 3) {
+			if (disMode > 2) {
```
Comment (ret2libc) [inline libr/core/graph.c]: instead of the ++ and if, i think it's more idiomatic to just do `disMode = (disMode + 1) % 3`
