### PR TITLE
(Fix #6927) Added info about loaded config files when R_DEBUG is set

### LINKED ISSUE #6927: Add loaded config file in R_DEBUG display
```
Cannot open /usr/local/lib/radare2/1.3.0-git//.
Cannot open /usr/local/lib/radare2/1.3.0-git//..
PLUGIN HANDLER 0x7fab0d442950 0x10e2684e0
Cannot find symbol 'radare_plugin' in library '/usr/local/lib/radare2/1.3.0-git//bin_xtr_dyldcache.dylib'
...
```

Should also have

```
USER CONFIG loaded from /XXX/XXX/radare2rc
USER CONFIG loaded from /XXX/XXX/radare2rc
```

So it's easier to debug user issue related to wrong config file.

### PR DESCRIPTION
**Pull request by xarkes**
This should do the trick. Also, I applied the r_file_is_regular function to the 2 firsts files as it is used a few lines below.

### CODE REVIEW

File: binr/radare2/radare2.c [hunk 1]
```diff
@@ -277,17 +277,30 @@ static int rabin_delegate(RThread *th) {
 #endif
 
 static void radare2_rc(RCore *r) {
+	char* env_debug = r_sys_getenv ("R_DEBUG");
+	bool has_debug = false;
+	if (env_debug) {
+		has_debug = true;
+		free (env_debug);
```
Comment (radare) [inline binr/radare2/radare2.c]: use R_FREE
