### PR TITLE
Fix #6411 - pseudo for AVR

### LINKED ISSUE #6411: Wrong AVR 'mul' description on pseudo asm
When setting asm.pseudo = true on AVR, the following instruction
`429f           mul r20, r18 `

gets 'translated' as:
`429f           r20 *= r18`

when it should be something like:
`429f           r1:r0 = r20*r18`

### PR DESCRIPTION
**Pull request by wargio**

### CODE REVIEW

File: libr/asm/p/asm_avr.c [hunk 1]
```diff
@@ -423,8 +423,8 @@ RAsmPlugin r_asm_plugin_avr = {
 		"ATmega168,"
 		"ATmega328p,"
 		"ATmega32u4,"
-	        "ATmega1280,"
-	        "ATmega2560,"
+	    "ATmega1280,"
```
Comment (radare) [inline libr/asm/p/asm_avr.c]: use tabs

File: libr/config.h.meson [hunk 2]
```diff
@@ -234,6 +234,7 @@
      &r_parse_plugin_mreplace, \
      &r_parse_plugin_ppc_pseudo, \
      &r_parse_plugin_sh_pseudo, \
+     &r_parse_plugin_avr_pseudo, \
```
Comment (radare) [inline libr/config.h.meson]: we should indent those meson files with tabs too

File: libr/parse/p/parse_avr_pseudo.c [hunk 3]
```diff
@@ -0,0 +1,224 @@
...
+	int i, len = strlen (data);
+	char w0[WSZ];
+	char w1[WSZ];
+	char w2[WSZ];
+	char w3[WSZ];
+	char w4[WSZ];
+	char *buf, *ptr, *optr, *par;
+
+	// malloc can be slow here :?
+	if (!(buf = malloc (len + 1)))
```
Comment (radare) [inline libr/parse/p/parse_avr_pseudo.c]: missing braces
