### PR TITLE
mdmp: fix googlefuzz crash (fix #11235)

### LINKED ISSUE #11235: One more googlefuzz crash
[clusterfuzz-testcase-minimized-ia_fuzz-5730103170957312.dms.zip](https://github.com/radare/radare2/files/2320828/clusterfuzz-testcase-minimized-ia_fuzz-5730103170957312.dms.zip)

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

File: libr/bin/format/mdmp/mdmp.c [hunk 1]
```diff
@@ -521,7 +546,10 @@ static bool r_bin_mdmp_init_directory_entry(struct r_bin_mdmp_obj *obj, struct m
 		break;
 	case COMMENT_STREAM_W:
 		/* TODO: Not yet fully parsed or utilised */
-		obj->streams.comments_w = obj->b->buf + entry->location.rva;
+		obj->streams.comments_w = r_buf_get_at (obj->b, entry->location.rva, NULL);
```
Comment (radare) [inline libr/bin/format/mdmp/mdmp.c]: using r_buf_get_at () is a bad idea because this only works with some RBuffer backends. so, for example if you are trying to parse an MDMP from an IO RBuffer (which only uses a file descriptor to operate), , the r_buf_get_at will return NULL and fail. The reason to keep r_buf_get_at is to have a way to get a pointer inside the buffer when we know for sure that the backend supports it.

**Comment by radare** [comment]
the alternative is requires copying memory which is not an ideal solution either. But i know other RBin plugins have been fixed in the same way

File: libr/bin/format/mdmp/mdmp.c (hunk 1 above)
Comment (ret2libc) [reply libr/bin/format/mdmp/mdmp.c]: What do you suggest as a general solution?

Comment (radare) [reply libr/bin/format/mdmp/mdmp.c]: wel i would merge this as is, because the solution is to have a wrapper api that holds temporal buffers or copy all the time
