### PR TITLE
Remove agft tiny graph edges on by default

### LINKED ISSUE #9962: `agft` is broken
Check on any single function.

@cyanpencil see this please too.

### PR DESCRIPTION
**Pull request by cyanpencil**
This should close #9962 

Now `agft`, and other commands which print tiny graphs to stdout (not interactive) won't print tiny graph edges.

Also refactored some code to use `r_core_cmdf` which is a lot more cleaner than constructing strings and then passing them to `r_core_cmd0`

### CODE REVIEW

**Comment by XVilka** [comment]
Failed test:
```
Diff: --- /tmp/r2-regressions//cmd_project-R1BFVr/exp	2018-05-23 09:05:30.610455644 +0000
+++ /tmp/r2-regressions//cmd_project-R1BFVr/out	2018-05-23 09:05:30.642456235 +0000
@@ -1,3 +1,3 @@
-37
-3
-5
+0
+2
+1
[  ]  19  cmd_types: tp                            
[XX]
```

File: libr/core/cmd_anal.c [hunk 1]
```diff
@@ -5994,12 +5993,8 @@ static void cmd_anal_graph(RCore *core, const char *input) {
...
 		case 'w':
 		case ' ': {
-			char *cmd = r_str_newf ("ag-; .agx* %lld; agg%c;", 
-				input[2] ? r_num_math (core->num, input + 2) : core->offset, input[1]);
-			if (cmd && *cmd) {
-				r_core_cmd0 (core, cmd);
-			}
-			free (cmd);
+			ut64 addr = input[2] ? r_num_math (core->num, input + 2) : core->offset;
+			r_core_cmdf (core, "ag-; .agx* %lld; agg%c;", addr, input[1]);
```
Comment (radare) [inline libr/core/cmd_anal.c]: use PFMT64d

File: libr/core/cmd_anal.c [hunk 2]
```diff
@@ -6045,13 +6040,9 @@ static void cmd_anal_graph(RCore *core, const char *input) {
 		case 'w':
 		case ' ': {
 			core->graph->is_callgraph = true;
-			char *cmd = r_str_newf ("ag-; .agc* %lld; agg%c;",
-				input[2] ? r_num_math (core->num, input + 2) : core->offset, input[1]);
-			if (cmd && *cmd) {
-				r_core_cmd0 (core, cmd);
-			}
+			ut64 addr = input[2] ? r_num_math (core->num, input + 2) : core->offset;
+			r_core_cmdf (core, "ag-; .agc* %lld; agg%c;", addr, input[1]);
```
Comment (radare) [inline libr/core/cmd_anal.c]: use PFMT64d

File: libr/core/cmd_anal.c [hunk 3]
```diff
@@ -6108,12 +6099,8 @@ static void cmd_anal_graph(RCore *core, const char *input) {
...
 		case 'd':
 		case ' ': {
-			char *cmd = r_str_newf ("ag-; .aga* %lld; agg%c;",
-				input[2] ? r_num_math (core->num, input + 2) : core->offset, input[1]);
-			if (cmd && *cmd) {
-				r_core_cmd0 (core, cmd);
-			}
-			free (cmd);
+			ut64 addr = input[2] ? r_num_math (core->num, input + 2): core->offset;
+			r_core_cmdf (core, "ag-; .aga* %lld; agg%c;", addr, input[1]);
```
Comment (radare) [inline libr/core/cmd_anal.c]: use PFMT64d

File: libr/core/cmd_anal.c [hunk 4]
```diff
@@ -5722,7 +5722,10 @@ static void cmd_agraph_print(RCore *core, const char *input) {
 		break;
 	case 't':// "aggt" - tiny graph
 		core->graph->is_tiny = true;
+		int e = r_config_get_i (core->config, "graph.edges");
```
Comment (radare) [inline libr/core/cmd_anal.c]: add {} braces

**Comment by XVilka** [comment]
@cyanpencil can you please address those comments and rebase?

**Comment by cyanpencil** [comment]
Done, also changed %lld with PFMT64d from other parts of ag* code
