### PR TITLE
Fix #7373. add '~str~?' support

### LINKED ISSUE #7373: ~str~? not working
should do the same as ~?str

### PR DESCRIPTION
**Pull request by qrux0**

### CODE REVIEW

File: libr/core/cmd.c [hunk 1]
```diff
@@ -1191,8 +1191,43 @@ static int cmd_system(void *data, const char *input) {
 	return ret;
 }
 
+static void
```
Comment (radare) [inline libr/core/cmd.c]: all this stuff goes in 1 line

File: libr/core/cmd.c [hunk 2]
```diff
@@ -1191,8 +1191,43 @@ static int cmd_system(void *data, const char *input) {
...
+prepare_intgrep(char *cmd, const char *quotestr)
+{
+	char *ptr;
+	int len = strlen (cmd);
+
+	//  search and modify '~str~?' into '~?str'
+	if (r_str_endswith (cmd, "~?") && len > 4 && cmd[len - 3] != '\\') {
```
Comment (radare) [inline libr/core/cmd.c]: check length first because that doesnt implies any string processing so you can skip false positives asap

File: libr/core/cmd.c [hunk 3]
```diff
@@ -1191,8 +1191,43 @@ static int cmd_system(void *data, const char *input) {
...
+		// try to find second '~' occurence
+		cmd[len - 2] = '\0';
+		ptr = (char *)r_str_lastbut (cmd, '~', quotestr);
+		if (ptr && ptr > cmd && *(ptr - 1) != '\\') {
+			memmove (ptr + 2, ptr + 1, strlen(ptr + 1));
```
Comment (radare) [inline libr/core/cmd.c]: missing space before (

File: libr/core/cmd.c [hunk 4]
```diff
@@ -1657,10 +1685,7 @@ static int r_core_cmd_subst_i(RCore *core, char *cmd, char *colon) {
 				r_cons_break_push (NULL, NULL);
 				recursive_help (core, cmd);
 				r_cons_break_pop ();
-				//grep the content
-				if (ptr[2] == '~') {
-					r_cons_grep (ptr + 3);
-				}
+				prepare_intgrep(ptr + 2, "`");
```
Comment (radare) [inline libr/core/cmd.c]: missing space before (

File: libr/core/cmd.c [hunk 5]
```diff
@@ -1862,23 +1887,12 @@ static int r_core_cmd_subst_i(RCore *core, char *cmd, char *colon) {
...
-		return  true;
+		return true;
 	}
-	if (ptr && *cmd != '.') {
-		*ptr = '\0';
-		ptr++;
-		cmd = r_str_chop (cmd);
-		r_cons_grep (ptr);
+	if (*cmd != '.') {
+		prepare_intgrep(cmd, quotestr);
```
Comment (radare) [inline libr/core/cmd.c]: missing space

File: libr/core/cmd.c [hunk 6]
```diff
@@ -1191,8 +1191,43 @@ static int cmd_system(void *data, const char *input) {
...
+			ptr[1] = '?';
+		} else {
+			// second '~' is not finded, restore original '~'
+			cmd[len - 2] = '~';
+		}
+	}
+
+	/* grep the content */
+	ptr = (char *)r_str_lastbut (cmd, '~', quotestr);
+	if (ptr && ptr>cmd) {
```
Comment (radare) [inline libr/core/cmd.c]: spaces around >

**Comment by qrux0** [comment]
Thanks for review, fixed that.

File: libr/core/cmd.c [hunk 7]
```diff
@@ -1191,8 +1191,42 @@ static int cmd_system(void *data, const char *input) {
 	return ret;
 }
 
+static void prepare_intgrep(char *cmd, const char *quotestr)
```
Comment (radare) [inline libr/core/cmd.c]: brace opens in the same line

**Comment by radare** [comment]
can u add tests?

**Comment by radare** [comment]
i would prefer to put all the logic of grepping inside rcons

**Comment by radare** [comment]
let's merge for now, we can fix those comments later. thanks!
