### PR TITLE
Fix #10050 - null deref in cmd_search

### LINKED ISSUE #10050: Null deref in cmd_search.c:2031
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits                             | 16.04.1 Ubuntu x86_64
| File format of the file you reverse      | ELF
| Architecture/bits of the file            | x86/64
| r2 -v          | radare2 2.6.0-git 18193 @ linux-x86-64 git.2.5.0-206-gbb2f7c9 commit: bb2f7c92117e5d9dbe0b6e83162411cae260cc16 build: 2018-05-08__11:49:23
| r2 -V | https://gist.github.com/fcasal/75b79f13ad691d3145cdd7b8b1c4b73a

### TLDR
Segfault caused by null deref in search

### Steps to reproduce the behaviour
```
mandlebro@machine$ r2 --
[0x00000000]> /c
Segmentation fault (core dumped)
```

The offending line is 2031 of cmd_search.c
```c
2029		if (!param->boundaries) {
2030			map = R_NEW0 (RIOMap);
2031			map->fd = core->io->desc->fd;
```
where core->io->desc is NULL.

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

File: libr/core/cmd_search.c [hunk 1]
```diff
@@ -1317,7 +1317,7 @@ static int r_core_search_rop(RCore *core, RInterval search_itv, int opt, const c
 			result = false;
 			goto bad;
 		}
-		map->fd = core->io->desc->fd;
+		map->fd = r_io_fd_get_current (core->io);
```
Comment (ret2libc) [inline libr/core/cmd_search.c]: about this kind of NULL deref... my question is: why is there a NULL there?

Comment (radare) [reply libr/core/cmd_search.c]: because if you open no file there's no current desc
