### PR TITLE
Fix agw command

### LINKED ISSUE #11187: agw is broken
Related: https://github.com/radareorg/cutter/pull/650

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows 10 x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/64
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.9.0-git 19238 @ windows-x86-64 git.2.8.0-159-g0030dd64b commit: 0030dd64bb8b265ca9916c1fa7a4a92d132c2c60 build: 22.08.2018__11:08:48,692018-02-17__11:08:27

**Export to file:**
```
[0x1400012e0]> agw a.out
Saving to file  a.out ...
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```

Invoked command:
`agfd @ 0x1400012e0 > a.dot;!C:\Program Files (x86)\Graphviz2.38\bin\dot.exe -Tgif -oa.out a.dot;`

**Display graph:**
```
[0x1400012e0]> agw
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
```
Invoked command: 
`agfd @ 0x1400012e0 > a.dot;!C:\Program Files (x86)\Graphviz2.38\bin\dot.exe -Tgif -o6 a.dot;`

WAT `-o6` ???????????

### PR DESCRIPTION
**Pull request by pelijah**
(fix #11187)
* Fix memleak in r_file_path()
* r_file_path() returns quoted path if it contains whitespaces

### CODE REVIEW

File: libr/util/file.c [hunk 1]
```diff
@@ -242,17 +242,22 @@ R_API char *r_file_path(const char *bin) {
 				*ptr = '\0';
 				file = r_str_newf (R_JOIN_2_PATHS ("%s", "%s%s"), str, bin, extension);
 				if (r_file_exists (file)) {
+					if (strchr (file, ' ')) {
+						char *tmp = file;
+						file = r_str_newf ("\"%s\"", file);
```
Comment (radare) [inline libr/util/file.c]: use the r_str api to escape chars instead of quoting it because that introduces other kind of vulnerabilities

File: libr/core/cmd_anal.c [hunk 2]
```diff
@@ -5904,27 +5904,35 @@ static char *getViewerPath() {
...
+#if __WINDOWS__
+	if (dotPath[0] == '\"') {
+		quotes = "\"";
 	}
-	if (r_file_exists (dotPath)) {
-		if (save_path && *save_path) {
-			cmd = r_str_newf ("%s > a.dot;!%s -T%s -o%s a.dot;", r2_cmd, dotPath, ext, save_path);
+#endif
+	if (save_path && *save_path) {
+		cmd = r_str_newf ("%s > a.dot;!%s%s -T%s -o%s a.dot%s;",
```
Comment (radare) [inline libr/core/cmd_anal.c]: what about using ./ and then mv using the C api ? instead of escaping chars, checking boundaries, etc

File: libr/util/file.c (hunk 1 above)
Comment (pelijah) [reply libr/util/file.c]: Is it possible to escape whitespace on Windows?

File: libr/core/cmd_anal.c (hunk 2 above)
Comment (pelijah) [reply libr/core/cmd_anal.c]: What do you mean under "./"?

**Comment by radare** [comment]
save the file in the current directory, so you dont care about spaces or path lengths, and then use r_file_copy() or (_move() which is not implemented yet) to move that file
