### PR TITLE
Major rework to the native debugger (esp on Linux)

### LINKED ISSUE #4907: Breakpoints inside loops do not fire properly without swstep
Try the following script:

```
e scr.color=0
e dbg.swstep=false
db sym.called_in_loop
dc
dr PC
dc
dr PC
dc
dr PC
dk 9
```

I'll PR this and other tests to r2-regressions soon.

### PR DESCRIPTION
**Pull request by jduck**
TODO. Test this PR on:

* [x] Linux
* [ ] FreeBSD
* [ ] NetBSD
* [x] OSX
* [ ] Windows

The major contribution here is completely re-worked breakpoint hit/recoil
handling. This work fixes #4907 and lays the ground work for future native
debugger improvements (multi-threading, etc).

NOTE: Please see comments marked with XXX as they include puzzlement and
questions.

A full list of changes includes:

* Give a human friendly type to enums
* Change many wait functions to return RDebugReasonType
* Better return checking (from r_debug_reg_sync, r_bp_restore)
* Optimized register synchronization
* Lots of comments and whitespace changes
* Improved inferior death detection

Handle EXIT_PID events differently than DEAD process events

* Move breakpoint/recoil handling to wait/cont/step

Rather than handing breakpoint related things inside cmd_debug.c, do that
inside the r_debug API functions. This seems like the most logical place for it
to live since it should apply to just about any platform/architecture.  This
also centralizes calling into "cmd.bp" handling via the CoreBind callback.

* Track how the caller wishes to continue

It turns out that handling break point recoils is very complicated. The ptrace
API on Linux returns SIGTRAP for just about every type of operation (not just
breakpoints getting hit). Add the "recoil_mode" flag to indicate whether we are
single-stepping or continuing and whether or not we are inside the recoil.

* Proper handling for swstep=true

Since r_debug_step_soft calls r_debug_continue, it's already hitting the recoil
case there. Move the recoil handling from r_debug_step to r_debug_step_hard
only.

For the swstep=true case, special handling is required inside r_debug_recoil.
By resetting all of the breakpoints except the one we just hit, we ensure we
can step the original instruction and hit the new swstep breakpoint. Add a new
bp function called r_bp_restore_except to do this.

To make matters worse, we cannot use a BreakpointItem pointer because that
leads to a use-after-free condition. Instead, we the breakpoint address
instead.

Now breakpoints should work regardless of the swtep setting.

* Always call the recoil before continuing

Some callers of r_debug_continue might not have ever inserted any breakpoints
before. If we don't restore breakpoints before each call to the underlying
continue we won't hit them.

* Hide software step breakpoint events from the user

When a breakpoint even happens due to a software-step, hide it from the user.
They aren't really breakpoints as far as they are concerned.

* Improve process exit handling on Linux

There are three types of process exiting events on Linux:

1. PTRACE_EVENT_EXIT occurs just before a process exits. It's not possible to
prevent it from exiting, but it can be used to inspect the pre-exit state.
2. The process can exit for a variety of reasons and we can notice when we call
waitpid(2).
3. The process could die randomly on us :-/

On Windows, h->wait will return R_DEBUG_REASON_EXIT_PID, but it's more likely
on Linux to find out the process is already dead.

* Check more bits within waitpid status

We can often make a decision about what happened strictly by looking at the
status returned from waitpid. In other cases, we need to call
r_debug_handle_signals.

If we reach the end of this function without knowing what happened, consider it
an error.

### CODE REVIEW

File: libr/core/cmd_debug.c [hunk 1]
```diff
@@ -2779,12 +2705,7 @@ static int cmd_debug_step (RCore *core, const char *input) {
 	switch (input[1]) {
 	case 0:
 		r_reg_arena_swap (core->dbg->reg, true);
-		r_debug_reg_sync (core->dbg, R_REG_TYPE_GPR, false);
 		r_debug_step (core->dbg, times);
-		if (checkbpcallback (core)) {
```
Comment (radare) [inline libr/core/cmd_debug.c]: iirc regsync is done before step because BSD requires to pass the updated PC in the PT_STEP/PT_CONT calls

File: libr/core/cmd_debug.c [hunk 2]
```diff
@@ -3108,7 +3016,7 @@ static int cmd_debug(void *data, const char *input) {
 			NULL
 		};
 		RDebugInfo *rdi = r_debug_info (core->dbg, input+2);
-		int stop = r_debug_stop_reason(core->dbg);
+		RDebugReasonType stop = r_debug_stop_reason(core->dbg);
```
Comment (radare) [inline libr/core/cmd_debug.c]: missing space

File: libr/core/cmd_debug.c [hunk 3]
```diff
@@ -3121,7 +3029,7 @@ static int cmd_debug(void *data, const char *input) {
 				P ("signum=%d\n", core->dbg->reason.signum);
 				P ("sigpid=%d\n", core->dbg->reason.tid);
 				P ("addr=0x%"PFMT64x"\n", core->dbg->reason.addr);
-				P ("inbp=%s\n", core->dbg->reason.bpi? "true": "false");
+				P ("inbp=%s\n", core->dbg->reason.bp_addr? "true": "false");
```
Comment (radare) [inline libr/core/cmd_debug.c]: there's r_str_bool for this

Comment (radare) [inline libr/core/cmd_debug.c]: to reduce the amount of "true" and "false" strings in the final binaries :P

File: libr/core/cmd_debug.c [hunk 4]
```diff
@@ -3144,7 +3052,7 @@ static int cmd_debug(void *data, const char *input) {
 				P ("\"signum\":%d,", core->dbg->reason.signum);
 				P ("\"sigpid\":%d,", core->dbg->reason.tid);
 				P ("\"addr\":%"PFMT64d",", core->dbg->reason.addr);
-				P ("\"inbp\":%s,", core->dbg->reason.bpi? "true": "false");
+				P ("\"inbp\":%s,", core->dbg->reason.bp_addr? "true": "false");
```
Comment (radare) [inline libr/core/cmd_debug.c]: same as above

File: libr/debug/debug.c [hunk 5]
```diff
@@ -26,40 +26,150 @@ R_API void r_debug_info_free (RDebugInfo *rdi) {
...
+ *
+ * Thus, we have two functions to handle these situations.
+ * r_debug_bp_hit handles stage 1.
+ * r_debug_recoil handles stage 2.
+ */
+static int r_debug_bp_hit(RDebug *dbg, RRegItem *pc_ri, ut64 pc) {
+	RBreakpointItem *b;
+
+	/* if we are tracing, update the tracing data */
+	if (dbg->trace->enabled)
```
Comment (radare) [inline libr/debug/debug.c]: add braces

File: libr/debug/debug.c [hunk 6]
```diff
@@ -26,40 +26,150 @@ R_API void r_debug_info_free (RDebugInfo *rdi) {
...
-			dbg->reason.type = R_DEBUG_REASON_BREAKPOINT;
-			dbg->reason.bpi = r_bp_get_at (dbg->bp, addr-recoil);
-			dbg->reason.addr = addr - recoil;
-			r_reg_set_value (dbg->reg, ri, addr-recoil);
-			if (r_reg_get_value (dbg->reg, ri) != (addr-recoil)) {
-				eprintf ("r_debug_recoil: Cannot set program counter\n");
+
+	/* see if we really have a breakpoint here... */
+	b = r_bp_get_at (dbg->bp, pc - dbg->bpsize);
+	if (!b) /* we don't. nothing left to do */
```
Comment (radare) [inline libr/debug/debug.c]: braces

File: libr/debug/debug.c [hunk 7]
```diff
@@ -26,40 +26,150 @@ R_API void r_debug_info_free (RDebugInfo *rdi) {
...
+		dbg->reason.bp_addr = 0;
+		return true;
+	}
+
+	/* setup our stage 2 */
+	dbg->reason.bp_addr = b->addr;
+
+	/* check if cur bp demands tracing or not */
+	if (b->trace)
+		eprintf("hit tracepoint at: %" PFMT64x "\n", pc);
```
Comment (radare) [inline libr/debug/debug.c]: use single eprintf with %s b->trace?"trace":"break"

File: libr/debug/debug.c [hunk 8]
```diff
@@ -26,40 +26,150 @@ R_API void r_debug_info_free (RDebugInfo *rdi) {
...
+		/* otherwise, avoid recursion */
+		return true;
 	}
-	return false;
+
+	/* we have entered recoil! */
+	dbg->recoil_mode = rc_mode;
+
+	/* step over the place with the breakpoint and let the caller resume */
+	if (r_debug_step (dbg, 1) != 1)
```
Comment (radare) [inline libr/debug/debug.c]: missing brackets

File: libr/debug/debug.c [hunk 9]
```diff
@@ -26,40 +26,150 @@ R_API void r_debug_info_free (RDebugInfo *rdi) {
...
+ *
+ * if a breakpoint was just hit, we need step over that instruction before
+ * allowing the caller to proceed as desired.
+ *
+ * if the user wants to step, the single step here does the job.
+ */
+static int r_debug_recoil(RDebug *dbg, RDebugRecoilMode rc_mode) {
+	/* if bp_addr is not set, we must not have actually hit a breakpoint */
+	if (!dbg->reason.bp_addr) {
+		goto enable_breakpoints;
```
Comment (radare) [inline libr/debug/debug.c]: uhm i dont like this goto much here. maybe just return enable_breakpoints(); and put that code in a separate static function

File: libr/debug/debug.c [hunk 10]
```diff
@@ -406,35 +514,78 @@ R_API int r_debug_stop_reason(RDebug *dbg) {
...
+
+			/* get the program coounter */
+			pc_ri = r_reg_get (dbg->reg, dbg->reg->name[R_REG_NAME_PC], -1);
+			if (!pc_ri)  /* couldn't find PC?! */
+				return R_DEBUG_REASON_ERROR;
+
+			/* get the value */
+			pc = r_reg_get_value (dbg->reg, pc_ri);
+
+			if (!r_debug_bp_hit (dbg, pc_ri, pc))
```
Comment (radare) [inline libr/debug/debug.c]: imssing braces

File: libr/debug/debug.c [hunk 11]
```diff
@@ -448,6 +599,9 @@ R_API int r_debug_step_soft(RDebug *dbg) {
 		ut32 r32[2];
 	} sp_top;
 
+	if (dbg->recoil_mode == R_DBG_RECOIL_NONE)
```
Comment (radare) [inline libr/debug/debug.c]: add braces

File: libr/debug/debug.c [hunk 12]
```diff
@@ -505,43 +662,63 @@ R_API int r_debug_step_soft(RDebug *dbg) {
...
-	if (r_debug_is_dead (dbg)) {
-		return false;
-	}
-
+	/* who calls this without giving a positive number? */
 	if (steps < 1) {
 		steps = 1;
 	}
 
+	if (r_debug_is_dead (dbg))
```
Comment (radare) [inline libr/debug/debug.c]: braces.

File: libr/debug/debug.c [hunk 13]
```diff
@@ -505,43 +662,63 @@ R_API int r_debug_step_soft(RDebug *dbg) {
...
+	reason = r_debug_wait (dbg);
+	/* TODO: handle better */
+	if (reason == R_DEBUG_REASON_ERROR)
+		return false;
+	if (reason == R_DEBUG_REASON_DEAD || r_debug_is_dead (dbg))
+		return false;
+	return true;
 }
 
 R_API int r_debug_step(RDebug *dbg, int steps) {
```
Comment (radare) [inline libr/debug/debug.c]: maybe r_debug_step() should be boolified

File: libr/debug/debug.c [hunk 14]
```diff
@@ -848,15 +1015,25 @@ R_API int r_debug_continue_syscalls(RDebug *dbg, int *sc, int n_sc) {
...
+		/* XXX(jjd): actually one stop is before the syscall, the other is
+		 * after.  this allows you to inspect the arguments before and the
+		 * return value after... */
 		r_debug_step (dbg, 1);
 #endif
 		dbg->h->contsc (dbg, dbg->pid, 0); // TODO handle return value
 		// wait until continuation
-		r_debug_wait (dbg);
+		reason = r_debug_wait (dbg);
+		if (reason == R_DEBUG_REASON_DEAD || r_debug_is_dead (dbg))
```
Comment (radare) [inline libr/debug/debug.c]: braces

Comment (radare) [inline libr/debug/debug.c]: sounds like dupe check

File: libr/debug/p/debug_native.c [hunk 15]
```diff
@@ -225,9 +225,14 @@ static int r_debug_native_continue (RDebug *dbg, int pid, int tid, int sig) {
 	#warning "r_debug_native_continue not supported on this platform"
 	return -1;
 #else
-	void *data = (void*)(size_t)((sig != -1) ? sig : dbg->reason.signum);
-	//eprintf ("continuing with signal %d ...\n", dbg->reason.signum);
-	return ptrace (PTRACE_CONT, pid, NULL, data) == 0;
+	int contsig;
+
+	if (sig != -1)
```
Comment (radare) [inline libr/debug/p/debug_native.c]: use ternary operator

File: libr/debug/p/debug_native.c [hunk 16]
```diff
@@ -225,9 +225,14 @@ static int r_debug_native_continue (RDebug *dbg, int pid, int tid, int sig) {
 	#warning "r_debug_native_continue not supported on this platform"
 	return -1;
 #else
-	void *data = (void*)(size_t)((sig != -1) ? sig : dbg->reason.signum);
-	//eprintf ("continuing with signal %d ...\n", dbg->reason.signum);
-	return ptrace (PTRACE_CONT, pid, NULL, data) == 0;
+	int contsig;
```
Comment (radare) [inline libr/debug/p/debug_native.c]: and assign the value in the definition line

File: libr/debug/p/native/linux/linux_debug.c [hunk 17]
```diff
@@ -47,31 +59,90 @@ int linux_handle_signals (RDebug *dbg) {
...
+ * If something went horribly wrong, we return ..._ERROR;
+ *
+ * NOTE: This API was added in Linux 2.5.46
+ */
+RDebugReasonType linux_ptrace_event (RDebug *dbg, int pid, int status) {
+	ut32 pt_evt;
+	ut32 data;
+
+	/* we only handle stops with SIGTRAP here */
+	if (!WIFSTOPPED(status) || WSTOPSIG(status) != SIGTRAP)
```
Comment (radare) [inline libr/debug/p/native/linux/linux_debug.c]: braces

File: libr/include/r_reg.h [hunk 18]
```diff
@@ -71,10 +79,10 @@ enum {
 
 typedef struct r_reg_item_t {
 	char *name;
-	int type;
-	int size;	/* 8,16,32,64 ... 128/256 ??? */
-	int offset;      // offset in data structure
-	int packed_size; /* 0 means no packed register, 1byte pack, 2b pack... */
+	RRegisterType type;
```
Comment (radare) [inline libr/include/r_reg.h]: indenting comments with spaces is fine. ideally we shouldnt be indenting them

File: libr/debug/debug.c (hunk 13 above)
Comment (jduck) [inline libr/debug/debug.c]: I like that it returns the number of successful steps that occurred TBH.

File: libr/debug/debug.c (hunk 14 above)
Comment (jduck) [inline libr/debug/debug.c]: One is a flag and one tries ```kill(pid, 0)```. I am trying to avoid doing an extra syscall here for no reason.

File: libr/debug/debug.c (hunk 13 above)
Comment (radare) [inline libr/debug/debug.c]: Then we should be consistent in returning 0 instead of false

File: libr/debug/debug.c (hunk 14 above)
Comment (radare) [inline libr/debug/debug.c]: Ok :)

File: libr/include/r_debug.h [hunk 19]
```diff
@@ -186,30 +186,30 @@ typedef struct r_debug_t {
 	char *arch;
 	int bits; /// XXX: MUST SET ///
 
-	int pid;    	/* selected process id */
-	int tid;    	/* selected thread id */
-	int forked_pid;	/* last pid created by fork */
+	int pid; /* selected process id */
+	int tid; /* selected thread id */
+	int forked_pid; /* last pid created by fork */
 	RList *threads; /* XXX This is platform-specific !!! */
```
Comment (radare) [inline libr/include/r_debug.h]: dont think so :D threads are a common concept on all platforms

Comment (radare) [inline libr/include/r_debug.h]: the comment refers to the fact that the data stored in there is handled different on each platform, so it makes it not handy for external use.

File: libr/core/cmd_debug.c [hunk 20]
```diff
@@ -2729,17 +2729,17 @@ static int cmd_debug_step (RCore *core, const char *input) {
...
+			step_until_inst (core, input + 3);
 			break;
 		case 'e':
-			step_until_esil (core, input+3);
+			step_until_esil (core, input + 3);
 			break;
 		case ' ':
 			r_reg_arena_swap (core->dbg->reg, true);
-			step_until (core, r_num_math (core->num, input+2)); // XXX dupped by times
+			step_until (core, r_num_math (core->num, input + 2)); // XXX dupped by times
```
Comment (radare) [inline libr/core/cmd_debug.c]: should be +3

Comment (radare) [inline libr/core/cmd_debug.c]: what about using a var instead of input +3 many times?

File: libr/bp/bp.c [hunk 21]
```diff
@@ -164,8 +164,8 @@ static RBreakpointItem *r_bp_add(RBreakpoint *bp, const ut8 *obytes, ut64 addr,
 		/* XXX: endian .. use bp->endian */
 		// XXX for hw breakpoints there are no bytes
 		ret = r_bp_get_bytes (bp, b->bbytes, size, 0, 0);
-		if (ret == 0) {
-			eprintf ("Cannot get breakpoint bytes. No r_bp_use()?\n");
+		if (ret != size) {
+			eprintf ("Cannot get breakpoint bytes. No r_bp_use()?\n"); //XXX(jjd): what is r_bp_use ?
```
Comment (radare) [inline libr/bp/bp.c]: is the api to select which bp plugin to use. aka arch/bits

File: libr/bp/io.c [hunk 22]
```diff
@@ -3,6 +3,24 @@
 #include <r_bp.h>
 #include "../config.h"
 
+R_API void r_bp_restore_one(RBreakpoint *bp, RBreakpointItem *b, int set) {
```
Comment (radare) [inline libr/bp/io.c]: set is bool

File: libr/core/cmd_debug.c [hunk 23]
```diff
@@ -1994,8 +1932,10 @@ static void r_core_cmd_bp(RCore *core, const char *input) {
 		bpi = r_bp_get_at (core->dbg->bp, addr);
 		if (bpi) {
 			//bp->enabled = !bp->enabled;
+			// XXX(jjd): this ^^ is what I would think toggling means...
 			r_bp_del (core->dbg->bp, addr);
 		} else {
+			// XXX(jjd): does t his need an address validity check??
 			bpi = r_debug_bp_add (core->dbg, addr, hwbp, NULL, 0);
```
Comment (radare) [inline libr/core/cmd_debug.c]: if any check. it should be done inside r_debug_bp_add

File: libr/core/cmd_debug.c [hunk 24]
```diff
@@ -1994,8 +1932,10 @@ static void r_core_cmd_bp(RCore *core, const char *input) {
 		bpi = r_bp_get_at (core->dbg->bp, addr);
 		if (bpi) {
 			//bp->enabled = !bp->enabled;
+			// XXX(jjd): this ^^ is what I would think toggling means...
```
Comment (radare) [inline libr/core/cmd_debug.c]: yep its toggling

File: libr/debug/debug.c [hunk 25]
```diff
@@ -628,55 +806,42 @@ R_API int r_debug_continue_kill(RDebug *dbg, int sig) {
...
-		retwait = r_debug_wait (dbg);
+
+		//XXX(jjd): why? //dbg->reason.signum = 0;
+
+		reason = r_debug_wait (dbg);
+
 #if __WINDOWS__
-		if (retwait != R_DEBUG_REASON_DEAD) {
+		if (reason != R_DEBUG_REASON_DEAD) {
+			// XXX(jjd): returning a thread id?!
```
Comment (radare) [inline libr/debug/debug.c]: the one that caused the event

File: libr/debug/debug.c [hunk 26]
```diff
@@ -848,15 +1015,25 @@ R_API int r_debug_continue_syscalls(RDebug *dbg, int *sc, int n_sc) {
...
 		r_debug_step (dbg, 1);
 #endif
 		dbg->h->contsc (dbg, dbg->pid, 0); // TODO handle return value
 		// wait until continuation
-		r_debug_wait (dbg);
+		reason = r_debug_wait (dbg);
+		if (reason == R_DEBUG_REASON_DEAD || r_debug_is_dead (dbg))
+			break;
+		if (reason != R_DEBUG_REASON_STEP)
+			break;
```
Comment (radare) [inline libr/debug/debug.c]: braces

File: libr/debug/p/debug_native.c [hunk 27]
```diff
@@ -273,84 +285,107 @@ static int r_debug_native_wait (RDebug *dbg, int pid) {
...
-					status = R_DEBUG_REASON_NEW_PID;
-				else status = R_DEBUG_REASON_UNKNOWN;
-			}
+	// TODO: switch status and handle reasons here
+#if __linux__ && defined(PT_GETEVENTMSG)
+	reason = linux_ptrace_event (dbg, pid, status);
+#endif // __linux__
+
+	/* propagate errors */
+	if (reason == R_DEBUG_REASON_ERROR)
```
Comment (radare) [inline libr/debug/p/debug_native.c]: missing braces

File: libr/debug/p/debug_native.c [hunk 28]
```diff
@@ -273,84 +285,107 @@ static int r_debug_native_wait (RDebug *dbg, int pid) {
...
+			 *
+			 * this might modify dbg->reason.signum
+			 */
+			if (!r_debug_handle_signals (dbg))
+				return R_DEBUG_REASON_ERROR;
+			reason = dbg->reason.type;
+		} else if (WIFCONTINUED (status)) {
+			eprintf ("child continued...\n");
+			reason = R_DEBUG_REASON_NONE;
+		} else if (status == 1) {
```
Comment (radare) [inline libr/debug/p/debug_native.c]: we shuold use a constant instead of an immediate R_DEBUG_REASON_SIGNAL

File: libr/debug/p/debug_native.c [hunk 29]
```diff
@@ -273,84 +285,107 @@ static int r_debug_native_wait (RDebug *dbg, int pid) {
...
+			/* XXX(jjd): does this actually happen? */
+			eprintf ("EEK DEAD DEBUGEE!\n");
+			reason = R_DEBUG_REASON_DEAD;
+		} else if (status == 0) {
```
Comment (radare) [inline libr/debug/p/debug_native.c]: 0 is R_DEBUG_REASON_NONE

File: libr/debug/p/debug_native.c [hunk 30]
```diff
@@ -273,84 +285,107 @@ static int r_debug_native_wait (RDebug *dbg, int pid) {
...
+#endif // __linux__
+
+	/* propagate errors */
+	if (reason == R_DEBUG_REASON_ERROR)
+		return reason;
+
+	/* we don't know what to do yet, let's try harder to figure it out. */
+	if (reason == R_DEBUG_REASON_UNKNOWN) {
+		if (WIFEXITED (status)) {
+			eprintf ("child exited with status %d\n", WEXITSTATUS(status));
```
Comment (radare) [inline libr/debug/p/debug_native.c]: missing space

File: libr/debug/p/native/linux/linux_debug.c [hunk 31]
```diff
@@ -47,31 +59,90 @@ int linux_handle_signals (RDebug *dbg) {
...
 	ut64 addr = 0; /* should be eip */
 	//ut32 data = 0;
 	//printf("NATIVE STEP over PID=%d\n", dbg->pid);
 	addr = r_debug_reg_get (dbg, "PC");
-	ret = ptrace (PTRACE_SINGLESTEP, dbg->pid,
-			(void*)(size_t)addr, 0);
-	linux_handle_signals (dbg);
+	//eprintf ("NATIVE STEP over PID=%d at 0x%" PFMT64x "\n", dbg->pid, addr);
+	ret = ptrace (PTRACE_SINGLESTEP, dbg->pid, (void*)(size_t)addr, 0);
+	//XXX(jjd): why?? //linux_handle_signals (dbg);
```
Comment (radare) [inline libr/debug/p/native/linux/linux_debug.c]: SIGWINCH and such

File: libr/debug/trace.c [hunk 32]
```diff
@@ -42,32 +42,32 @@ R_API int r_debug_trace_tag (RDebug *dbg, int tag) {
...
-				oldpc = addr;
-				return true;
-			} else eprintf ("trace_pc: cannot get opcode size at 0x%"PFMT64x"\n", addr);
-		} //else eprintf ("trace_pc: cannot read memory at 0x%"PFMT64x"\n", addr);
-	} else eprintf ("trace_pc: cannot get program counter\n");
+				r_debug_trace_add (dbg, oldpc, op.size);
+			}
+			oldpc = pc;
+			return true;
+		}
```
Comment (radare) [inline libr/debug/trace.c]: wrong indent. use more braces

File: libr/include/r_debug.h (hunk 19 above)
Comment (jduck) [inline libr/include/r_debug.h]: makes sense. threads will be the next thing to tackle.

File: libr/core/cmd_debug.c (hunk 24 above)
Comment (jduck) [inline libr/core/cmd_debug.c]: I think we discussed this the other day. Would you be against putting it back to the enabled = !enabled method instead of deleting breakpoints and recreating them when toggling ?  Otherwise it would be impossible to toggle something unless you use the address

File: libr/debug/p/debug_native.c (hunk 29 above)
Comment (jduck) [inline libr/debug/p/debug_native.c]: status and reason are different things ;-)

File: libr/debug/trace.c (hunk 32 above)
Comment (jduck) [inline libr/debug/trace.c]: I'd prefer to invert some conditions and make this more readable that way. Nesting like this sucks for readability.

Comment (radare) [inline libr/debug/trace.c]: agree

File: libr/debug/p/debug_native.c (hunk 29 above)
Comment (radare) [inline libr/debug/p/debug_native.c]: oh right, i read it wrong. if it’s there is must be for something :P maybe git blame will light the commit that introduced this and we can identify the platform

File: libr/core/cmd_debug.c (hunk 20 above)
Comment (jduck) [inline libr/core/cmd_debug.c]: There's not really a great place to declare it here. Anyway I'd be in favor of something larger that made command argument handling much cleaner throughout. I just don't think this PR is the right place for it.

Comment (radare) [inline libr/core/cmd_debug.c]: yeah just a random comment. np

File: libr/core/cmd_debug.c (hunk 23 above)
Comment (jduck) [inline libr/core/cmd_debug.c]: The goal for ```r_debug_bp_add``` is to add an R_API function to automate much of adding a breakpoint. Unfortunately "validAddress" uses "core" to determine validity. I'd guess this is the reason that function lives in cmd_debug.c instead of debug.c.

File: libr/debug/debug.c (hunk 25 above)
Comment (jduck) [inline libr/debug/debug.c]: Okay, but this is the only return from the function that is non-boolean.

Comment (jduck) [inline libr/debug/debug.c]: I don't think it's possible, but what if TID is 0?

File: libr/debug/p/debug_native.c (hunk 29 above)
Comment (jduck) [inline libr/debug/p/debug_native.c]: This is new code from me ;-) I just don't know if this will ever happen hehe.

File: libr/debug/p/debug_native.c (hunk 28 above)
Comment (jduck) [inline libr/debug/p/debug_native.c]: I don't think this will ever happen, but who knows. I should probably just remove it.

File: libr/debug/p/debug_native.c (hunk 29 above)
Comment (jduck) [inline libr/debug/p/debug_native.c]: Seems like it came from 233982c965f0f077a5241254e0b5bd0b13e0a27b and has something to do with dead inferiors. No clue on platform...

File: libr/debug/p/native/linux/linux_debug.c (hunk 31 above)
Comment (jduck) [inline libr/debug/p/native/linux/linux_debug.c]: SIGWINCH and friends should still come through the ptrace API. that is, waitpid will return and indicate the process is stopped by a signal. linux_handle_signals is called through r_debug_handle_signals from r_debug_native_wait.

It's also called from r_debug_native_step, which is probably also wrong (like this commented out invocation).

Am I missing something?

File: libr/debug/trace.c (hunk 32 above)
Comment (jduck) [inline libr/debug/trace.c]: I have a branch (https://github.com/jduck/radare2/tree/trace-brace-fix) queued up for PR following this one landing.

File: libr/core/cmd_debug.c (hunk 3 above)
Comment (jduck) [inline libr/core/cmd_debug.c]: Addressed in 3ef151cd3171a2227af1af40aacf548729134308

File: libr/debug/debug.c (hunk 11 above)
Comment (jduck) [inline libr/debug/debug.c]: fixed

File: libr/core/cmd_debug.c (hunk 1 above)
Comment (jduck) [inline libr/core/cmd_debug.c]: I put it back to be safe. Hopefully can revisit once there is better platform / test coverage.

File: libr/debug/debug.c (hunk 13 above)
Comment (jduck) [inline libr/debug/debug.c]: I have queued up a branch (https://github.com/jduck/radare2/tree/step-return-consistency) for PR following this one.

File: libr/debug/debug.c (hunk 25 above)
Comment (radare) [inline libr/debug/debug.c]: Yup

Comment (radare) [inline libr/debug/debug.c]: Yep that case will be problematic

File: libr/debug/p/native/linux/linux_debug.c (hunk 31 above)
Comment (radare) [inline libr/debug/p/native/linux/linux_debug.c]: Nope, your reasonign seems correct. Maybe this was dropped for debugging purposes and i guess that it can be removed

File: libr/debug/debug.c (hunk 13 above)
Comment (radare) [inline libr/debug/debug.c]: Ok will test this patch on mac and see if it breaks something, if not ill merge. The patch lgtm

**Comment by radare** [comment]
Tested on OSX and it seems to work fine, didnt noticed any regression. maybe @skuater can test later on windows. but lets merge it for now :) so you are not blocked
