### PR TITLE
FIX #7597 use and sort fresh funcitonlist instead of the existing one…

### LINKED ISSUE #7597: 'pdf' disassembles the wrong function after 'afl'
When analyzing hmmapi.dll (part of IE, attached), I encountered the following weird behavior of 'pdf' command for one function - 0x4261555. This function is the first one after the import section.
Not using afl - everything works correctly (outputs of 'afl' and 'pdf' are edited for brevity sake):
```
[0x0426337f]> aac
[0x0426337f]> s 0x4261555
[0x04261555]> pdf
/ (fcn) fcn.04261555 48
|   fcn.04261555 ();
|              ; CALL XREF from 0x04261cf9 (fcn.04261cce)
|           0x04261555      8bff           mov edi, edi
|           0x04261557      56             push esi
|           0x04261558      8bf0           mov esi, eax
|           0x0426155a      33c0           xor eax, eax
|           0x0426155c      8bca           mov ecx, edx
...
```

But here's what happens if I try to disassemble the same function **after** using 'afl':

```
[0x0426337f]> aac
[0x0426337f]> afl
0x04261028    4 4    -> 17   sym.imp.KERNEL32.dll_SetUnhandledExceptionFilter
0x0426102c    4 4    -> 17   sym.imp.KERNEL32.dll_UnhandledExceptionFilter
0x04261030    5 4    -> 17   sym.imp.KERNEL32.dll_GetCurrentProcess
0x04261034   28 108  -> 102  sym.imp.KERNEL32.dll_TerminateProcess
0x042610a0  127 1253 -> 1163 sym.imp.KERNEL32.dll_DisableThreadLibraryCalls
0x04261555   10 48           fcn.04261555 <--- this function is the first one after the import section
0x0426158a    9 74           fcn.0426158a
...
[0x0426337f]> s 0x4261555
[0x04261555]> pdf
/ (fcn) sym.imp.KERNEL32.dll_DisableThreadLibraryCalls 1163
|   sym.imp.KERNEL32.dll_DisableThreadLibraryCalls (int arg_13h, int arg_61h);
|       !   ; arg int arg_13h @ ebp+0x13
|       !   ; arg int arg_61h @ ebp+0x61
|       !      ; CALL XREF from 0x04261666 (fcn.04261652)
|       !      ; DATA XREF from 0x04261666 (fcn.04261652)
|       |   0x042610a0      ae             scasb al, byte es:[edi]
|       |   0x042610a1      19e3           sbb ebx, esp
|      ,==< 0x042610a3      7700           ja 0x42610a5
|      `--> 0x042610a5      0000           add byte [eax], al
|       |   0x042610a7  ~   00a59ba47300   add byte [ebp + 0x73a49b], ah
|       |   ;-- imp.SHELL32.dll_ShellExecuteA:
|       !      ; CALL XREF from 0x04261f91 (fcn.04261ef0)
|       !      ; DATA XREF from 0x04261f91 (fcn.04261ef0)
|       |   0x042610a8      a5             movsd dword es:[edi], dword ptr [esi]
|       |   0x042610a9      9b             wait
|       |   0x042610aa      a4             movsb byte es:[edi], byte ptr [esi]

```

Notice, it thinks the function's start address is 0x042610a0, but this address belongs to the import section:
0x042610a0  127 1253 -> 1163 sym.imp.KERNEL32.dll_DisableThreadLibraryCalls

'pd' still works fine, so it must be some some memory corruption issue happening in afl

I updated radare2 from git minutes before reporting this issue, so I'm running the latest version.

[hmmapi.tar.gz](https://github.com/radare/radare2/files/1030949/hmmapi.tar.gz)

### PR DESCRIPTION
**Pull request by rlaemmert**
… on print

### CODE REVIEW

File: libr/core/canal.c [hunk 1]
```diff
@@ -2214,11 +2211,8 @@ R_API int r_core_anal_fcn_list(RCore *core, const char *input, const char *rad)
 		fcn_list_default (core, fcns, false);
 		break;
 	}
-	//make sure you don't free core->anal->fcns
-	if (input && core->anal->fcns != fcns) {
-		// The list does not own the its members, so don't purge.
-		free (fcns);
-	}
+
+	free (fcns);
```
Comment (radare) [inline libr/core/canal.c]: this leaks. you cant free" a list.. it must use r_list_free or r_list_destroy.. unset the->free ptr if you just wanna free the container and not the content
