### PR TITLE
libr: Fix fflush (stdin) (fix #12053)

### LINKED ISSUE #12053: fflush (stdin) is undefined in C
In line https://github.com/radare/radare2/blob/a0844ef2c3a2e2852e975634686f0eca4a447093/libr/cons/input.c#L254. `fdin` is only assigned by `stdin`, so `fflush (fdin)` is actually `fflush (stdin)`.  In standard C, `fflush` works only with output/update stream, not input stream.

Reference:
- https://stackoverflow.com/questions/18170410/what-is-the-use-of-fflushstdin-in-c-programming

### PR DESCRIPTION
**Pull request by lzutao**
In standard C, `fflush` works only with output/update stream, not input stream.

### CODE REVIEW

File: libr/cons/input.c [hunk 1]
```diff
@@ -230,6 +230,13 @@ R_API int r_cons_arrow_to_hjkl(int ch) {
 	return ch;
 }
 
+static inline void flush_istream(FILE *in_stream) {
+	int ch;
+	while ((ch = fgetc(in_stream)) != '\n' && ch != EOF) {
```
Comment (radare) [inline libr/cons/input.c]: missing space before (

Comment (radare) [reply libr/cons/input.c]: also, i dont think we want to call fgetc to skip chars in fgets(). did you tried your patch? because it seems to be like we can just remove the fflush line

Comment (lzutao) [reply libr/cons/input.c]: ok

Comment (lzutao) [reply libr/cons/input.c]: I have built it locally, it seems that r2 interactive run ok.

**Comment by lzutao** [comment]
I'm testing but now I having problem with installing multiple version of r2.

```r2
% /opt/radare2/git/usr/bin/r2 -V
3.0.1-153-gfabc04ae3  r2
3.0.1  r_anal
3.0.1  r_lib
3.0.1  r_egg
3.0.1  r_asm
3.0.1  r_bin
3.0.1  r_cons
3.0.1  r_flag
3.0.1  r_core
3.0.1  r_crypto
3.0.1  r_bp
3.0.1  r_debug
3.0.1  r_hash
3.0.1  r_fs
3.0.1  r_io
3.0.1  r_magic
3.0.1  r_parse
3.0.1  r_reg
3.0.1  r_sign
3.0.1  r_search
3.0.1  r_syscall
3.0.1  r_util
WARNING: r2 library versions mismatch!
% /opt/radare2/git/usr/bin/r2 -v
WARNING: r2 library versions mismatch! See r2 -V
radare2 3.1.0-git 19868 @ linux-x86-64 git.3.0.1-153-gfabc04ae3
commit: fabc04ae3a7af1641a299d616572074073d4eb3f build: 2018-11-06__14:10:21
% /opt/radare2/usr/bin/r2 -v    
radare2 3.0.1 19867 @ linux-x86-64 git.3.0.1
commit: addb7f21e73073600fd6205e385fa096084701f5 build: 2018-11-06__14:00:28
% /opt/radare2/usr/bin/r2 -V
3.0.1  r2
3.0.1  r_anal
3.0.1  r_lib
3.0.1  r_egg
3.0.1  r_asm
3.0.1  r_bin
3.0.1  r_cons
3.0.1  r_flag
3.0.1  r_core
3.0.1  r_crypto
3.0.1  r_bp
3.0.1  r_debug
3.0.1  r_hash
3.0.1  r_fs
3.0.1  r_io
3.0.1  r_magic
3.0.1  r_parse
3.0.1  r_reg
3.0.1  r_sign
3.0.1  r_search
3.0.1  r_syscall
3.0.1  r_util
```

**Comment by lzutao** [comment]
Oh, my mistake, I laid old r2 libraries in /usr (removed it manually), but now two r2 versions installed in /opt do not work.

```r2
% /opt/radare2/usr/bin/r2 -V
/opt/radare2/usr/bin/r2: error while loading shared libraries: libr_core.so: cannot open shared object file: No such file or directory
% /opt/radare2/git/usr/bin/r2 -V
/opt/radare2/git/usr/bin/r2: error while loading shared libraries: libr_core.so: cannot open shared object file: No such file or directory
% ls /opt/radare2/git/usr/lib
pkgconfig               libr_bp.so                libr_crypto.so            libr_fs.so              libr_magic.so             libr_shlr.a
radare2                 libr_bp.so.3.1.0-git      libr_crypto.so.3.1.0-git  libr_fs.so.3.1.0-git    libr_magic.so.3.1.0-git   libr_socket.so
libr_anal.so            libr_config.so            libr_debug.so             libr_hash.so            libr_parse.so             libr_socket.so.3.1.0-git
libr_anal.so.3.1.0-git  libr_config.so.3.1.0-git  libr_debug.so.3.1.0-git   libr_hash.so.3.1.0-git  libr_parse.so.3.1.0-git   libr_syscall.so
libr_asm.so             libr_cons.so              libr_egg.so               libr_io.so              libr_reg.so               libr_syscall.so.3.1.0-git
libr_asm.so.3.1.0-git   libr_cons.so.3.1.0-git    libr_egg.so.3.1.0-git     libr_io.so.3.1.0-git    libr_reg.so.3.1.0-git     libr_util.so
libr_bin.so             libr_core.so              libr_flag.so              libr_lang.so            libr_search.so            libr_util.so.3.1.0-git
libr_bin.so.3.1.0-git   libr_core.so.3.1.0-git    libr_flag.so.3.1.0-git    libr_lang.so.3.1.0-git  libr_search.so.3.1.0-git
```

It seems that r2 needs to be installed in /usr.

**Comment by radare** [comment]
Use rpath (see configure help), set ldlibrarypath or configure ldconf. 

Or just use sys/install which does that automatically

**Comment by radare** [comment]
Alternatively you can also build it statically

File: libr/cons/input.c [hunk 2]
```diff
@@ -230,6 +230,13 @@ R_API int r_cons_arrow_to_hjkl(int ch) {
 	return ch;
 }
 
+static inline void flush_istream(FILE *in_stream) {
+	int ch;
+	while ((ch = fgetc (in_stream)) != '\n' && ch != EOF) {
```
Comment (radare) [inline libr/cons/input.c]: imho the fflush(stdin) should be nonblock. i'm still unsure if that's the behaviour we are expecting. cc @ret2libc

Comment (ret2libc) [reply libr/cons/input.c]: I didn't dig too much into this PR, though I've seen that it doesn't work as it is and I've provided ways to test the actual code that is being changed. With default parameters, you don't even reach this code usually. I'm ok with replacing `fflush(stdin)`, though this does not seem the right way to do it :(

**Comment by lzutao** [comment]
Just remove the `fflush (stdin)` line, I think you're right @radare .

**Comment by lzutao** [comment]
I don't see any cases that need to flush the input. Removed the `fflush (stdin)` line and tested with `r2 -e scr.fgets=true /bin/ls` I haven't seen anything different.
