### PR TITLE
Pe resource name #11981

### LINKED ISSUE #11981: Wrong resource names in PE files
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu x64, wsl, Arch Linux x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86_32 x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.1.0-git 20010 @ linux-x86-64 git.3.0.1-80-g6080edf
commit: 6080edf13b207d23d7b3faf09b96aa10dffd6cc2 build: 2018-10-29__15:31:34

### Expected behavior

While executing `iR` or `iRj`, the right resource name should be shown

### Actual behavior
Currently, radare2 wrongfully parses the resource name from the PE resource directories. More accurately, he passes the ID of the resource instead of parsing the relevant name from the table

### Steps to reproduce the behavior 
 - Open a PE file (`r2 file.exe`)
 - Execute `iR` or `iRj~{}`
 - Compare the shown resource name to the name as shown in another resource parser (e.g Resource Hacker)
 - radare2 shows a wrong name

### Additional Logs, screenshots, source-code,  configuration dump, ...

r2 output "2874":
image

Expected Name "MAINICON":
image

Drag and drop zip archives containing the Additional info here, don't use external services or link.

### PR DESCRIPTION
**Pull request by koffiedrinker**
If a resource has a name, then show it instead of showing a number/id.
Fixes #11981 

I used the malware with 64 resources (named and unnamed resources) from issue #12327

```
[koffiedrinker@ctf radare2]$ ./binr/radare2/radare2 ../e15040beca2635a66eb395162f39db9f23468e7bf9f00c9c62dd5913cd5f3850
 -- Control the signal handlers of the child process with the 'dk' command
[0x004b1660]> iR
...
Resource 19
  name: CURRENTFOLDER
  timestamp: Sat May 19 09:15:04 2012
  vaddr: 0x004a4b44
  size: 224
  type: BITMAP
  language: LANG_ENGLISH
Resource 20
  name: EXECUTABLE
  timestamp: Sat May 19 09:15:04 2012
  vaddr: 0x004a4c24
  size: 224
  type: BITMAP
  language: LANG_ENGLISH
...
Resource 63
  name: MAINICON
  timestamp: Sat May 19 09:15:04 2012
  vaddr: 0x004b64b4
  size: 20
  type: GROUP_ICON
  language: LANG_KOREAN
Resource 64
  name: 1
  timestamp: Sat May 19 09:15:04 2012
  vaddr: 0x004b64cc
  size: 832
  type: VERSION
  language: LANG_KOREAN
```

Note that this changes the JSON as well. the value for "name" is now always a string, not a number.

```
[...., {"name":"MAINICON", "index":63, "type":"GROUP_ICON", "vaddr":4940980, "size":20, "lang":"LANG_KOREAN", "timestamp":"Sat May 19 09:15:04 2012"}, {"name":"1", "index":64, "type":"VERSION", "vaddr":4941004, "size":832, "lang":"LANG_KOREAN", "timestamp":"Sat May 19 09:15:04 2012"}]
```

### CODE REVIEW

File: libr/core/cbin.c [hunk 1]
```diff
@@ -3253,7 +3253,7 @@ static void bin_pe_resources(RCore *r, int mode) {
 		}
 		ut64 vaddr = sdb_num_get (sdb, vaddrKey, 0);
 		int size = (int)sdb_num_get (sdb, sizeKey, 0);
-		int name = (int)sdb_num_get (sdb, nameKey, 0);
+		char *name = sdb_get (sdb, nameKey, 0);
```
Comment (radare) [inline libr/core/cbin.c]: use sdb_const_get() or remember to free `name`

File: libr/core/cbin.c [hunk 2]
```diff
@@ -3263,14 +3263,14 @@ static void bin_pe_resources(RCore *r, int mode) {
 		} else if (IS_MODE_RAD (mode)) {
 			r_cons_printf ("f resource.%d %d 0x%08"PFMT32x"\n", index, size, vaddr);
 		} else if (IS_MODE_JSON (mode)) {
-			r_cons_printf ("%s{\"name\":%d,\"index\":%d, \"type\":\"%s\","
+			r_cons_printf ("%s{\"name\":\"%s\", \"index\":%d, \"type\":\"%s\", "
```
Comment (radare) [inline libr/core/cbin.c]: will be good to switch to use the pj.c api in here too.maybe in another pr? or do you want to finish it in here?

File: libr/bin/format/pe/pe.c [hunk 3]
```diff
@@ -2264,6 +2265,16 @@ static void _parse_resource_directory(struct PE_(r_bin_pe_obj_t) *bin, Pe_image_
 			eprintf ("Warning: read resource entry\n");
 			break;
 		}
+		ut8 *resourceEntryName = NULL;
+		if (entry.u1.s.NameIsString) {
+			ut16 resourceEntryNameLength;
+			r_buf_read_at (bin->b, bin->resource_directory_offset + entry.u1.s.NameOffset, (ut8*)&resourceEntryNameLength, sizeof (ut16));
+
+			resourceEntryName = calloc (resourceEntryNameLength, sizeof (ut8));
```
Comment (radare) [inline libr/bin/format/pe/pe.c]: leak?

File: libr/core/cbin.c (hunk 1 above)
Comment (koffiedrinker) [reply libr/core/cbin.c]: Will fix.

File: libr/core/cbin.c (hunk 2 above)
Comment (koffiedrinker) [reply libr/core/cbin.c]: Seem straightforward to change. I'll do it in this PR.

File: libr/bin/format/pe/pe.c (hunk 3 above)
Comment (koffiedrinker) [reply libr/bin/format/pe/pe.c]: For "normal" PEs, the resourceEntryName will be passed to `_parse_resource_directory()` again in the last parameter and assigned to "name" in the `r_pe_resource` struct which will be freed in `_free_resources()`. I have to do it this way since the name is actually the name of the directory and not the name of the resource itself (see last picture of @ITAYC0HEN in his issue).

But I agree that there might be a memory leak if you have weird resource structures. I'll add a free in the cases where the resourceEntryName wouldn't end up in `r_pe_resource`.

**Comment by koffiedrinker** [comment]
this should fix it :)

File: libr/core/cbin.c [hunk 4]
```diff
@@ -3263,9 +3265,15 @@ static void bin_pe_resources(RCore *r, int mode) {
...
 			r_cons_printf ("f resource.%d %d 0x%08"PFMT32x"\n", index, size, vaddr);
 		} else if (IS_MODE_JSON (mode)) {
-			r_cons_printf ("%s{\"name\":\"%s\", \"index\":%d, \"type\":\"%s\", "
-					"\"vaddr\":%"PFMT64d", \"size\":%d, \"lang\":\"%s\", \"timestamp\":\"%s\"}",
-					index? ", ": "", name, index, type, vaddr, size, lang, timestr);
+			pj_o (pj);
+			pj_ks (pj, "name", name);
+			pj_ki (pj, "index", index);
+			pj_ks (pj, "type", type);
+			pj_ks (pj, "vaddr", sdb_fmt ("0x%08"PFMT64x, vaddr));
```
Comment (Maijin) [inline libr/core/cbin.c]: Use pj_kn, PFMT64 is annoying to parse

Comment (koffiedrinker) [reply libr/core/cbin.c]: done
