### PR TITLE
Fix #10719 line graph not correctly

### LINKED ISSUE #10719: Line graph not correctly
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | 32bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0-git 18877 @ linux-x86-64 git.2.7.0-20-g8db9631c9 commit: 8db9631c98b7792199c366bbda5cc3a6d5db6762 build: 2018-07-12__16:54:01

### Expected behavior
radare2 show line from `jle 0x804851f` to `0x804851f [gj]` graph blocks
screenshot_20180712_202013

### Actual behavior
screenshot_20180712_202013

### Steps to reproduce the behavior 
```
$ r2 -A ./check
:> s 0x8048550
:> VV
```
### Additional Logs, screenshots, source-code,  configuration dump, ...
[check.zip](https://github.com/radare/radare2/files/2188740/check.zip)

### PR DESCRIPTION
**Pull request by cyanpencil**
Closes #10719 
Basically the fix was letting r2 set up duplicate edges AT FIRST, 
then deleting them after r2 set up backedges.

Not allowing dup edges was interfering with backedges or edges drawing in general, in particular cases (where there was a backedge from a direct neighbour).

### CODE REVIEW

File: libr/core/graph.c [hunk 1]
```diff
@@ -2125,6 +2125,23 @@ static void get_bbupdate(RAGraph *g, RCore *core, RAnalFunction *fcn) {
 	core->anal->stackptr = saved_stackptr;
 }
 
+static void delete_dup_edges (RAGraph *g) {
```
Comment (XVilka) [inline libr/core/graph.c]: This would probably slow down graphs a bit, but correctness is more important

Comment (XVilka) [reply libr/core/graph.c]: Lets keep optimization for later then
