### PR TITLE
Fix #7376

### LINKED ISSUE #7376: Bad disassembly of fill-array-data-payload in Dalvik
r2 does not disassemble correctly data array payloads. For example, in the following, the **Dalvik** bytecode is creating an array data with values { 0xF, 0x74, 0x8 }, but the display below is incorrect:

```
           0x0007bec8      000301000300.  fill-array-data-payload 1, 3
; .. payload of 4 bytes
            0x0007bed0      0f74           return v116
            0x0007bed2      08000003       move-object/from16 v0, v768
```

1.  There is not a payload of 4 bytes, but of 3 bytes.
2.  The last two lines should not be interpreted as Dalvik bytecode. They are part of the array data payload. 0f 74 08
3. The last bytes 0003 are the head for a new fill-array-data-payload. See [https://source.android.com/devices/tech/dalvik/dalvik-bytecode#fill-array](here)

Same a little later:
```
            0x0007bed2      08000003       move-object/from16 v0, v768
            0x0007bed6      0100           move v0, v0
            0x0007bed8      0400           move-wide v0, v0
            0x0007beda      0000           nop
            0x0007bedc      6e72696f0003   invoke-virtual {},  ; 0x6f69
```
This is a bad disassembly, and should rather show an array data with 
```
              0x6E
              0x72
              0x69
              0x6F
```

To reproduce, Android/Ztorg sample sha256: 2c546ad7f102f2f345f30f556b8d8162bd365a7f1a52967fce906d46a2b0dac4
However, I assume the bug will show in any Dalvik bytecode using array-data.

### PR DESCRIPTION
**Pull request by h4ng3r**

### CODE REVIEW

File: libr/core/disasm.c [hunk 1]
```diff
@@ -34,8 +34,8 @@ static const char* r_vline_u[] = {
 	"├", // LINE_CROSS
 	"─", // LINE_HORIZ
 	"↑", // LINE_UP
- 	//"┌", // LUP_CORNER
-  	"┘", // LUP_CORNER
+	//"┌", // LUP_CORNER
```
Comment (radare) [inline libr/core/disasm.c]: Wat

File: libr/core/disasm.c [hunk 2]
```diff
@@ -243,7 +243,7 @@ static void ds_print_fcn_name(RDisasmState *ds);
 static void ds_print_as_string(RDisasmState *ds);
 static void ds_print_core_vmode(RDisasmState *ds);
 static void ds_print_dwarf(RDisasmState *ds);
-static void ds_print_asmop_payload(RDisasmState *ds);
+static void ds_print_asmop_payload(RDisasmState *ds, ut8 *buf);
```
Comment (radare) [inline libr/core/disasm.c]: Const ut8*?

File: libr/core/disasm.c [hunk 3]
```diff
@@ -2212,7 +2212,7 @@ static void ds_print_show_bytes(RDisasmState *ds) {
 			}
 			pad[j] = '\0';
 		} else {
-		    	pad[0] = 0;
+				pad[0] = 0;
```
Comment (radare) [inline libr/core/disasm.c]: Wring indent

File: libr/core/disasm.c [hunk 4]
```diff
@@ -2572,8 +2572,15 @@ static void ds_print_asmop_payload(RDisasmState *ds) {
 			break;
 		}
 	}
-	if (ds->asmop.payload != 0)
+	if (ds->asmop.payload != 0) {
 		r_cons_printf ("\n; .. payload of %d bytes", ds->asmop.payload);
+		if (r_config_get_i (ds->core->config, "asm.showpayloads")) {
```
Comment (radare) [inline libr/core/disasm.c]: Cache this var in ds_init and just use the value here to avoid resolving it on every iteration

File: libr/core/disasm.c [hunk 5]
```diff
@@ -2572,8 +2572,15 @@ static void ds_print_asmop_payload(RDisasmState *ds) {
...
+			int x = 0;
+			for (x; x < ds->asmop.payload; ++x) {
```
Comment (radare) [inline libr/core/disasm.c]: For convenience is better to init the var in the firstblock of the for

File: libr/core/disasm.c [hunk 6]
```diff
@@ -3686,7 +3693,7 @@ R_API int r_core_print_disasm(RPrint *p, RCore *core, ut64 addr, ut8 *buf, int l
 			ds_print_dwarf (ds);
 			ret = ds_print_middle (ds, ret);
 
-			ds_print_asmop_payload (ds);
+			ds_print_asmop_payload (ds, buf + idx);
```
Comment (radare) [inline libr/core/disasm.c]: I think yhat if u pass a buffer you'll have to pass the size of it too

File: libr/core/cconfig.c [hunk 7]
```diff
@@ -2010,6 +2010,7 @@ R_API int r_core_config_init(RCore *core) {
 	SETPREF ("asm.marks", "true", "Show marks before the disassembly");
 	SETPREF ("asm.cmtrefs", "false", "Show flag and comments from refs in disasm");
 	SETPREF ("asm.cmtpatch", "false", "Show patch comments in disasm");
+	SETPREF ("asm.showpayloads", "false", "Show payload bytes in disasm");
```
Comment (radare) [inline libr/core/cconfig.c]: maybe asm.payloads is enough, the "show" thing is implicity in all the subvars of asm.

File: libr/core/disasm.c [hunk 8]
```diff
@@ -2572,8 +2572,15 @@ static void ds_print_asmop_payload(RDisasmState *ds) {
 			break;
 		}
 	}
-	if (ds->asmop.payload != 0)
+	if (ds->asmop.payload != 0) {
 		r_cons_printf ("\n; .. payload of %d bytes", ds->asmop.payload);
+		if (r_config_get_i (ds->core->config, "asm.showpayloads")) {
+			int x = 0;
+			for (x; x < ds->asmop.payload; ++x) {
+				r_cons_printf("\n        0x%x", buf[ ds->oplen + x ]);
```
Comment (radare) [inline libr/core/disasm.c]: missing space before (

Comment (radare) [inline libr/core/disasm.c]: drop spaces in []

File: libr/core/disasm.c [hunk 9]
```diff
@@ -3066,7 +3073,7 @@ static void print_fcn_arg(RCore *core, const char *type, const char *name,
 	//r_cons_newline ();
 	r_cons_printf ("%s", type);
 	r_core_cmdf (core, "pf %s%s %s @ 0x%08" PFMT64x,
-		     (on_stack == 1) ? "*" : "", fmt, name, addr);
+			 (on_stack == 1) ? "*" : "", fmt, name, addr);
```
Comment (radare) [inline libr/core/disasm.c]: only 1 tab and no spaces to indent

File: libr/core/disasm.c [hunk 10]
```diff
@@ -4226,8 +4234,8 @@ R_API int r_core_print_disasm_json(RCore *core, ut64 addr, ut8 *buf, int nb_byte
 		}
 
 		r_cons_printf ("}");
-		i += oplen; // bytes
-		k += oplen; // delta from addr
+		i += oplen + asmop.payload; // bytes
```
Comment (radare) [inline libr/core/disasm.c]: this is not obeying asm.payload

Comment (h4ng3r) [inline libr/core/disasm.c]: it is

File: libr/core/disasm.c (hunk 1 above)
Comment (h4ng3r) [inline libr/core/disasm.c]: I dont know why is different...
