### PR TITLE
Fix #7509 - update blocksize when calling r_core_print_disasm_instruc…

### LINKED ISSUE #7509: broken r_core_print_disasm_instructions when using nb_bytes parameter
there seem to be a problem in some cases with r_core_print_disasm_instructions when using the nb_bytes parameter.

this can be easily reproduced with the following binary: https://github.com/JonathanSalwan/Triton/blob/master/src/examples/python/ctf-writeups/defcon-2016-baby-re/baby-re

just do (with PR #7508 ):
```
dcu main
af
pib
```
or even just:
```
dcu main
pI 300
```

### PR DESCRIPTION
**Pull request by kamou**
…tions with nb_bytes parameter

related to #7509

### CODE REVIEW

File: libr/core/disasm.c [hunk 1]
```diff
@@ -3876,6 +3876,11 @@ R_API int r_core_print_disasm_instructions(RCore *core, int nb_bytes, int nb_opc
 			nb_bytes = -nb_bytes;
 			core->offset -= nb_bytes;
 			r_core_read_at (core, core->offset, core->block, nb_bytes);
+		} else {
+			if (nb_bytes > core->blocksize) {
+				r_core_block_size (core, nb_bytes);
```
Comment (radare) [inline libr/core/disasm.c]: uhm is the block size restored back after disassembling?

Comment (radare) [inline libr/core/disasm.c]: will be good to have a test for this

Comment (kamou) [inline libr/core/disasm.c]: oh ok, not yet totally comfortable with r2 apis, I'll check for restoring the block size.
ok for a test.

Comment (kamou) [inline libr/core/disasm.c]: how can I check that ? just with "b" after executing the "pI 300" command ? because it is actually  displaying 0x100

Comment (kamou) [inline libr/core/disasm.c]: displaying core->blocksize at the end of the finction shows 0x12c whereas it was 0x100 at function entry, so I guess I do need to fix that.

Comment (kamou) [inline libr/core/disasm.c]: or I might be missing something. because two consecutive calls to pI 300 show a block size of 0x100 ant function r_core_print_disasm_instruc entry

Comment (kamou) [inline libr/core/disasm.c]: the blocksize restoring is done in cmd_print function (caller)
should I still make sure r_core_print_disasm_instruc restores blocksize ?

**Comment by radare** [comment]
can you add some tests for this? thanks!!

**Comment by kamou** [comment]
done: https://github.com/radare/radare2-regressions/pull/848
