### PR TITLE
Fix #12559 segmentation fault on iX command.

### LINKED ISSUE #12559: iX option segment fault
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             |  Ubuntu 16.04.3 LTS x86_64
| File format of the file you reverse (mandatory)      |  ELF
| Architecture/bits of the file (mandatory)            |  x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20508 @ linux-x86-64 git.3.1.3-139-ge7451c6
commit: e7451c6a0b074a4a1602f3ffcac1cc58ed25ecf3 build: 2018-12-25__10:39:26

### Expected behavior

Print error and exit if there is no source files available.

### Actual behavior

segment fault

### Steps to reproduce the behavior 

- `r2 -w -nn adminui.elf`
- `iX`

### Additional Logs, screenshots, source-code,  configuration dump, ...

Two files are included in the attachment:

- adminui.elf, the program
- core-r2.1564.xserver.1545706468, the core dump file for the program

[segmentfault.zip](https://github.com/radare/radare2/files/2707999/segmentfault.zip)

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

File: libr/core/cbin.c [hunk 1]
```diff
@@ -1014,6 +1014,12 @@ static int srclineCmp(const void *a, const void *b) {
 static int bin_source(RCore *r, int mode) {
 	RList *final_list = r_list_new ();
 	RBinFile * binfile = r->bin->cur;
+
+	if (!binfile) {
+		r_cons_printf ("[Error bin file]\n");
```
Comment (Maijin) [inline libr/core/cbin.c]: Use bprintf here please
