### PR TITLE
Fixes #13651: Added config var for max autocompletion array

### LINKED ISSUE #13651: RFE: Completion limit should be dynamic (not 4096)
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora x86_64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21672 @ linux-x86-64 git.3.4.1-32-g44eb2e26e commit: 44eb2e26e4fef1dd15a877019f417ea0922ea13b build: 2019-04-07__18:59:00

### Expected behavior

When loading multiple PE binaries via `oba`, i would like to walk through the symbols using the shell completion.

The problem is that the completion miss some of the symbols

### Actual behavior
The completion is missing some of the symbols

Look at the asciinema video I recorded.
I want to complete all the symbols which start by `sym.nt` (`ntoskrnl` or `ntdll`), and r2 immediately completes by `sym.ntdllxxxx`

### Steps to reproduce the behavior 
- [asciinema](https://asciinema.org/a/YWMwi7hBkkXSNuYFYvolYBeAT)

### Additional Logs, screenshots, source-code,  configuration dump, ...
I can share the binaries if necessary.

Thanks !

### PR DESCRIPTION
**Pull request by deepakchethan**

### CODE REVIEW

File: libr/core/cconfig.c [hunk 1]
```diff
@@ -1102,6 +1102,13 @@ static bool cb_str_escbslash(void *user, void *data) {
 	return true;
 }
 
+static bool cb_completion_maxtab (void *user, void *data) {
+    RCore *core = (RCore*) user;
```
Comment (XVilka) [inline libr/core/cconfig.c]: wrong indent.

Comment (deepakchethan) [reply libr/core/cconfig.c]: Fixed Indent :)
