### PR TITLE
Error on invalid b instruction FIX #5085

### LINKED ISSUE #5085: rasm2 wrong code instead of error
On invalid instruction rasm2 gives wrong code:

```
$ rasm2 -a arm -b16 "b lr"
fee7 -> b PC
```

Error message would be more desirable

### PR DESCRIPTION
**Pull request by Svenito**
If label resolves to an offset of 0, assume instruction invalid

Test added via PR radare/radare2-regressions#611

### CODE REVIEW

File: libr/asm/arch/arm/armass.c [hunk 1]
```diff
@@ -421,6 +421,10 @@ static int thumb_assemble(ArmOpcode *ao, ut64 off, const char *str) {
 	} else
 	if (!strcmpnull (ao->op, "b") || !strcmpnull (ao->op, "b.n")) {
 		//uncond branch : PC += 4 + (delta*2)
+		int offset = getnum (ao->a[0]);
+		if (offset == 0) {
```
Comment (radare) [inline libr/asm/arch/arm/armass.c]: oh! but thats not correct, because `b 0` is vaild. getnum should return -1 in case of fail, isnt?

Comment (Svenito) [inline libr/asm/arch/arm/armass.c]: True. I wrestled with this, because the `getnum` function uses `atoi` so there's no error condition. Also, -1 is technically also a valid number.

Does r2 codebase have a smarter way to accomplish this without needing RNum?

**Comment by radare** [comment]
https://www.freebsd.org/cgi/man.cgi?query=strtod&sektion=3&apropos=0&manpath=FreeBSD+10.3-RELEASE+and+Ports

**Comment by Svenito** [comment]
Had a look at those while I was searching, but wasn't sure if they are ok to use. New PR coming
