### PR TITLE
Fix #9870 , fix r_anal_type_get_size and handle enum type

### LINKED ISSUE #9870: r_anal_type_get_size returns wrong size
Struct size is not properly computed
```
[0x100001200]> to /tmp/pcap.h
[0x100001200]> ts
pcap_pktrec_tcp
pcap_file_hdr
pcap_pktrec_ether
pcak_pktrec_hdr
pcap_pktrec_ipv6
pcap_pktrec_ipv4
[0x100001200]> ts pcap_file_hdr
pf dwwdddE magic version_major version_minor this_zone ts_accuracy max_pkt_len (pcap_net)network
[0x100001200]> .ts pcap_file_hdr
         magic : 0x100001200 = 3850979413
 version_major : 0x100001204 = 0x5741
 version_minor : 0x100001206 = 0x5641
     this_zone : 0x100001208 = 1413567809
   ts_accuracy : 0x10000120c = 3967895635
   max_pkt_len : 0x100001210 = 1560
       network : 0x100001214 = network (enum pcap_net) = 0x41f78949
[0x100001200]> tss pcap_file_hdr
160
[0x100001200]>
```

160??? should be 24

### PR DESCRIPTION
**Pull request by sivaramaaa**
After this fix u get 

```
[0x00000000]> to ./pcap.h
[0x00000000]> ts
pcap_pktrec_tcp
pcap_file_hdr
pcap_pktrec_ether
pcak_pktrec_hdr
pcap_pktrec_ipv6
pcap_pktrec_ipv4 
[0x00000000]> tss pcap_file_hdr
24
```
pfs output : 
```
[0x00000000]> .ts*pcap_file_hdr
[0x00000000]> pfs.pcap_file_hdr
24
```

### CODE REVIEW

**Comment by radare** [comment]
<3

File: libr/anal/types.c [hunk 1]
```diff
@@ -81,11 +81,15 @@ R_API int r_anal_type_get_size(RAnal *anal, const char *type) {
 	}
 	const char *t = sdb_const_get (anal->sdb_types, tmptype, 0);
 	if (!t) {
+		if (!strncmp (tmptype, "enum ", 5)) {
+			//XXX: Need a proper way to determine size of enum
+			return 32;
```
Comment (radare) [inline libr/anal/types.c]: yes, but maybe let this to the user, or assume its the same as "int", but that depends on the compiler.. msvc doesnt support 64bit enums :_
