### PR TITLE
fixing type link consumes no bytes FIX #4359

### LINKED ISSUE #4359: Types in disasm doesnt consume bytes
See that there are some issues here:
```
$ r2 -
 -- One does not simply write documentation.
[0x00000000]> wx 33
[0x00000000]> tl int
[0x00000000]> pd 1
struct int {
0x00000000 = 51
}
            0x00000000      3300           xor eax, dword [rax]
[0x00000000]>
```
* [ ] struct int wtf
* [ ] links of offset=type should also sepcify a name
* [ ] those names doesnt need to be unique
* [ ] the offset of the next instruction should be `$$ + sizeof(typeIn($$))`

### PR DESCRIPTION
**Pull request by oddcoder**
fixing tl totally
refactoring types
implementing some api for types
Adding types profiles for x86 and x86_64 architectures (which is extendable to add types for other archs/operating systems)

### CODE REVIEW

File: libr/anal/anal.c [hunk 1]
```diff
@@ -11,38 +11,35 @@ R_LIB_VERSION(r_anal);
...
+	return 1;
+}
+
+R_API void r_anal_type_init(RAnal *anal) {
+	const char *anal_arch =  anal->cur->arch;
+	char *dbpath;
+	if (!strcmp (anal_arch, "x86")) {
+		Sdb *db;
+		#define TYPESPATH R2_LIBDIR"/radare2/"R2_VERSION"/fcnsign"
+		dbpath = r_str_newf(TYPESPATH"/types-%s-%d.sdb", anal_arch,
```
Comment (radare) [inline libr/anal/anal.c]: char *dbpath , the scope of this var is right in the same assignment block. also add spaces before ( and around defines (TYPESPATH...

File: libr/anal/anal.c [hunk 2]
```diff
@@ -11,38 +11,35 @@ R_LIB_VERSION(r_anal);
...
+	}
+	return 1;
+}
+
+R_API void r_anal_type_init(RAnal *anal) {
+	const char *anal_arch =  anal->cur->arch;
+	char *dbpath;
+	if (!strcmp (anal_arch, "x86")) {
+		Sdb *db;
+		#define TYPESPATH R2_LIBDIR"/radare2/"R2_VERSION"/fcnsign"
```
Comment (radare) [inline libr/anal/anal.c]: #define must start at the begining of the line to conform to C specs

File: libr/anal/types.c [hunk 3]
```diff
@@ -21,7 +21,7 @@ R_API int r_anal_type_set(RAnal *anal, ut64 at, const char *field, ut64 val) {
 	return false;
 }
 
-R_API void r_anal_type_del(RAnal *anal, const char *name) {
+R_API void r_anal_type_del (RAnal *anal, const char *name) {
```
Comment (radare) [inline libr/anal/types.c]: function signatures doesnt have space before (. the reason is because this way they can be easily grepped

File: libr/anal/types.c [hunk 4]
```diff
@@ -40,7 +40,105 @@ R_API void r_anal_type_del(RAnal *anal, const char *name) {
...
+		free (query);
+		return ret;
+	}
+	if (!strcmp (t, "struct")) {
+		char *query = r_str_newf ("%s.%s");
+		char *members = sdb_get (anal->sdb_types, query, 0);
+		char *next, *ptr = members;
+		int ret = 0;
+		free (query);
+		do{
```
Comment (radare) [inline libr/anal/types.c]: missing space

File: libr/anal/types.c [hunk 5]
```diff
@@ -40,7 +40,105 @@ R_API void r_anal_type_del(RAnal *anal, const char *name) {
...
+	const char *t = sdb_const_get (anal->sdb_types, type, 0);
+	if (!strcmp (t, "type")){
+		char *query = r_str_newf ("type.%s.size", type);
+		int ret;
+		ret = r_num_math (NULL, sdb_const_get (anal->sdb_types, query, 0));
+		free (query);
+		return ret;
+	}
+	if (!strcmp (t, "struct")) {
+		char *query = r_str_newf ("%s.%s");
```
Comment (radare) [inline libr/anal/types.c]: where are the two arguments?

File: libr/anal/types.c [hunk 6]
```diff
@@ -40,7 +40,105 @@ R_API void r_anal_type_del(RAnal *anal, const char *name) {
 	sdb_unset (DB, str, 0);
 }
 
-R_API char* r_anal_type_to_str(RAnal *a, const char *type) {
+R_API int r_anal_type_get_size (RAnal *anal, char *type) {
+	const char *t = sdb_const_get (anal->sdb_types, type, 0);
+	if (!strcmp (t, "type")){
+		char *query = r_str_newf ("type.%s.size", type);
+		int ret;
```
Comment (radare) [inline libr/anal/types.c]: assign and define at the same line

File: libr/anal/types.c [hunk 7]
```diff
@@ -40,7 +40,105 @@ R_API void r_anal_type_del(RAnal *anal, const char *name) {
...
+		ret = r_num_math (NULL, sdb_const_get (anal->sdb_types, query, 0));
```
Comment (radare) [inline libr/anal/types.c]: maybe r_num_get is enough? do this expression contain operations or it is just a tnumber? if its just a number you can use the sdb_num api and avoid extra steps

File: libr/anal/types.c (hunk 5 above)
Comment (radare) [inline libr/anal/types.c]: use sdb_fmt instead of messing with the heap

File: libr/anal/types.c [hunk 8]
```diff
@@ -40,7 +40,105 @@ R_API void r_anal_type_del(RAnal *anal, const char *name) {
...
+	if (!strcmp (t, "struct")) {
+		char *query = r_str_newf ("%s.%s");
+		char *members = sdb_get (anal->sdb_types, query, 0);
+		char *next, *ptr = members;
+		int ret = 0;
+		free (query);
+		do{
+			char *name = sdb_anext (ptr, &next);
+			query = r_str_newf ("%s.%s.%s", t, type, name);
+			char * subtype = strstr (sdb_get (anal->sdb_types, query, 0), ",");
```
Comment (radare) [inline libr/anal/types.c]: this memleaks. sdb_get returns a pointer to the heap. use sdb_const_get or so

Comment (radare) [inline libr/anal/types.c]: if you are checking for just a char, use strchr instead of strstr

File: libr/anal/types.c (hunk 5 above)
Comment (radare) [inline libr/anal/types.c]: query is redefined before using this wrongly assignment

File: libr/anal/types.c [hunk 9]
```diff
@@ -40,7 +40,105 @@ R_API void r_anal_type_del(RAnal *anal, const char *name) {
...
+	ls_foreach (sdb_list, sdb_iter, kv) {
+		if (strcmp (kv->value, "func")) {
+			continue;
+		}
+		RAnalFunction *fcn = r_anal_fcn_new ();
+		r_list_append (list, fcn);
+		//setting function name and return type
+		fcn->name = strdup (kv->key);
+		//setting function return type
+		key = r_str_newf ("func.%s.ret",kv->key);
```
Comment (radare) [inline libr/anal/types.c]: missing space after ,

File: libr/anal/types.c [hunk 10]
```diff
@@ -40,7 +40,105 @@ R_API void r_anal_type_del(RAnal *anal, const char *name) {
...
+		free (key);
+		free (value);
+		if (!args_n) {
+			continue;
+		}
+		//XXX we should handle as much calling conventions
+		//for as much architectures as we want here as we want here
+		fcn->vars = r_list_new ();
+		for (i = 0; i < args_n; i++) {
+			char *name;
```
Comment (radare) [inline libr/anal/types.c]: why that lonely char *name here?

File: libr/anal/types.c [hunk 11]
```diff
@@ -40,7 +40,105 @@ R_API void r_anal_type_del(RAnal *anal, const char *name) {
...
+		r_list_free (list);
+		return NULL;
+	}
+	return list;
+}
+
+R_API RAnalFunction *r_anal_get_function_type (RAnal *anal, const char *name) {
+	return 0;
+}
+R_API char* r_anal_type_to_str (RAnal *a, const char *type) {
```
Comment (radare) [inline libr/anal/types.c]: missing newline

File: libr/anal/types.c [hunk 12]
```diff
@@ -85,19 +183,22 @@ R_API int r_anal_type_frame_del (RAnal *anal, ut64 addr, const char *name) {
...
 		return true;
 	} 
 	// eprintf ("Cannot find type\n");
 	return false;
 }
-R_API int r_anal_type_unlink(RAnal *anal, ut64 addr){
-	char laddr[strlen("link.")+17];
-	snprintf (laddr, sizeof (laddr)-1, "link.%08"PFMT64x, addr);
+R_API int r_anal_type_unlink(RAnal *anal, ut64 addr) {
+	char *laddr = r_str_newf("link.%08"PFMT64x, addr);
```
Comment (radare) [inline libr/anal/types.c]: missing space

File: libr/anal/types.c [hunk 13]
```diff
@@ -85,19 +183,22 @@ R_API int r_anal_type_frame_del (RAnal *anal, ut64 addr, const char *name) {
...
+	if(!laddr) {
```
Comment (radare) [inline libr/anal/types.c]: missing space

File: libr/anal/types.c [hunk 14]
```diff
@@ -85,19 +183,22 @@ R_API int r_anal_type_frame_del (RAnal *anal, ut64 addr, const char *name) {
...
+		return false;
```
Comment (radare) [inline libr/anal/types.c]: same as above

File: libr/core/cmd_type.c [hunk 15]
```diff
@@ -341,24 +355,68 @@ static int cmd_type(void *data, const char *input) {
...
+				free (tmp);
+			} else {
+				eprintf ("unknown type %s\n", type);
+			}
+			free (type);
+			}
+			break;
+		case 's': {
+			int ptr;
+			char *addr = strdup (input+2);
```
Comment (radare) [inline libr/core/cmd_type.c]: missing spaces around +

File: libr/core/cmd_type.c [hunk 16]
```diff
@@ -341,24 +355,68 @@ static int cmd_type(void *data, const char *input) {
...
+			SdbKv *kv;
+			SdbListIter *sdb_iter;
+			SdbList *sdb_list = sdb_foreach_list (core->anal->sdb_types);
```
Comment (radare) [inline libr/core/cmd_type.c]: if you want performance dont use sdb_foreach_list. there's a callback-based way to iterate over an sdb (sdb_foreach()) that doesnt implies allocating the whole db into a new list that will be destroyed later

File: libr/core/cmd_type.c [hunk 17]
```diff
@@ -341,24 +355,68 @@ static int cmd_type(void *data, const char *input) {
...
+					continue;
+				}
+				linkptr = r_str_newf ("0x%s", kv->key + strlen ("link."));
+				if (ptr == r_num_math (NULL, linkptr)) {
+					linklist_readable (core, kv->key, kv->value);
+				}
+				free (linkptr);
+			}
+			free (addr);
+			ls_destroy (sdb_list);
```
Comment (radare) [inline libr/core/cmd_type.c]: what about ls_free ?

File: libr/core/cmd_type.c [hunk 18]
```diff
@@ -341,24 +355,68 @@ static int cmd_type(void *data, const char *input) {
...
+			SdbList *sdb_list = sdb_foreach_list (core->anal->sdb_types);
+			r_str_chop (addr);
+			ptr = r_num_math (NULL, addr);
+			//r_core_cmdf (core, "tl~0x%08"PFMT64x" = ", addr);
+			ls_foreach (sdb_list, sdb_iter, kv) {
+				char *linkptr;
+				if (strncmp (kv->key, "link.", strlen ("link."))) {
+					continue;
+				}
+				linkptr = r_str_newf ("0x%s", kv->key + strlen ("link."));
```
Comment (radare) [inline libr/core/cmd_type.c]: use sdb_fmt

File: libr/core/disasm.c [hunk 19]
```diff
@@ -2998,10 +2995,26 @@ R_API int r_core_print_disasm(RPrint *p, RCore *core, ut64 addr, ut8 *buf, int l
...
+		//TRY adding here
+		char *link_key = r_str_newf ("link.%08"PFMT64x, ds->addr + idx);
+		char *link_type = sdb_get (core->anal->sdb_types, link_key, 0);
+		free (link_key);
+		if (link_type) {
+			char *fmt = r_anal_type_format (core->anal, link_type);
+			if (fmt) {
+				r_cons_printf ("(%s)\n", link_type);
+				 r_core_cmdf (core, "pf %s @ 0x%08"PFMT64x"\n", fmt, ds->addr + idx);
+				 inc+= r_anal_type_get_size (core->anal, link_type)/8;
```
Comment (radare) [inline libr/core/disasm.c]: missing space

File: libr/core/disasm.c [hunk 20]
```diff
@@ -2998,10 +2995,26 @@ R_API int r_core_print_disasm(RPrint *p, RCore *core, ut64 addr, ut8 *buf, int l
 			}
 		}
 		ds_show_comments_right (ds);
-		ret = ds_disassemble (ds, buf+idx, len-idx);
-		if (ret == -31337) {
-			inc = ds->oplen;
-			continue;
+		//TRY adding here
+		char *link_key = r_str_newf ("link.%08"PFMT64x, ds->addr + idx);
```
Comment (radare) [inline libr/core/disasm.c]: use sdb_fmt

Comment (radare) [inline libr/core/disasm.c]: maybe adding helprs to construct those strings will make the code more readable

File: libr/core/disasm.c [hunk 21]
```diff
@@ -2998,10 +2995,26 @@ R_API int r_core_print_disasm(RPrint *p, RCore *core, ut64 addr, ut8 *buf, int l
...
+		char *link_type = sdb_get (core->anal->sdb_types, link_key, 0);
```
Comment (radare) [inline libr/core/disasm.c]: use sdb_const_get. you dont need that value in the heap

File: libr/core/disasm.c (hunk 19 above)
Comment (radare) [inline libr/core/disasm.c]: spaces

**Comment by radare** [comment]
please update asap :3

**Comment by radare** [comment]
also, can you write tests cases?

**Comment by radare** [comment]
pls rebase on top of master

File: libr/anal/types.c (hunk 10 above)
Comment (oddcoder) [inline libr/anal/types.c]: what is wrong with it ?

File: libr/core/cmd_type.c (hunk 16 above)
Comment (oddcoder) [inline libr/core/cmd_type.c]: not flexible enough

File: libr/anal/types.c (hunk 10 above)
Comment (radare) [inline libr/anal/types.c]: nah its fine. just felt bad for him
