### PR TITLE
Fix #5474: proposal of fix

### LINKED ISSUE #5474: r2 -H VAR
show value of given variable, useful for grabbing the plugindir, prefix path or so from makefiles or shellscripts

### PR DESCRIPTION
**Pull request by saucec0de**

### CODE REVIEW

File: binr/radare2/radare2.c [hunk 1]
```diff
@@ -197,6 +198,40 @@ static int main_help(int line) {
...
+		{ "PREFIX", R2_PREFIX },
+		{ "INCDIR", R2_INCDIR },
+		{ "LIBDIR", R2_LIBDIR },
+		{ "LIBEXT", R_LIB_EXT },
+		{ "RHOMEDIR", R2_HOMEDIR },
+		{ NULL, NULL }
+	};
+
+	if (var_name) {
+		while ( r2_vars[i].name ) {
```
Comment (radare) [inline binr/radare2/radare2.c]: drop those spaces after ( and before )

File: binr/radare2/radare2.c [hunk 2]
```diff
@@ -197,6 +198,40 @@ static int main_help(int line) {
...
+			if ( !strcmp (r2_vars[i].name, var_name) ) {
```
Comment (radare) [inline binr/radare2/radare2.c]: same here

File: binr/radare2/radare2.c [hunk 3]
```diff
@@ -197,6 +198,40 @@ static int main_help(int line) {
...
+				printf ("%s\n", r2_vars[i].value);
+				break;
+			}
+			i++;
+		}
+	} else {
+		while ( r2_vars[i].name ) {
```
Comment (radare) [inline binr/radare2/radare2.c]: and here

File: binr/radare2/radare2.c [hunk 4]
```diff
@@ -435,6 +476,7 @@ int main(int argc, char **argv, char **envp) {
 		case 'f': fullfile = 1; break;
 		case 'F': forcebin = optarg; break;
 		case 'h': help++; break;
+		case 'H': main_print_var(optarg); return 0; break;
```
Comment (radare) [inline binr/radare2/radare2.c]: missing space before (

File: binr/radare2/radare2.c [hunk 5]
```diff
@@ -144,6 +144,7 @@ static int main_help(int line) {
 		" -f           block size = file size\n"
 		" -F [binplug] force to use that rbin plugin\n"
 		" -h, -hh      show help message, -hh for long\n"
+		" -H, H [var]  display variable\n"
```
Comment (radare) [inline binr/radare2/radare2.c]: use `-H ([var])`

**Comment by radare** [comment]
the patch looks good after those minor fixes. but it will be nice to be more consistent with the env vars used. like what i did for ?!?:

```
[0x00000000]> ?!?
|Usage: !<cmd>  Run given command as in system(3)
| !                        list all historic commands
| !ls                      execute 'ls' in shell
| !!                       save command history to hist file
| !!ls~txt                 print output of 'ls' and grep for 'txt'
| .!rabin2 -rpsei ${FILE}  run each output line as a r2 cmd
| !echo $SIZE              display file size
| !=!                      enable remotecmd mode
| =!=                      disable remotecmd mode
|
Environment:
| R2_FILE                  file name
| R2_OFFSET                10base offset 64bit value
| R2_BYTES                 TODO: variable with bytes in curblock
| R2_XOFFSET               same as above, but in 16 base
| R2_BSIZE                 block size
| R2_ENDIAN                'big' or 'little'
| R2_IOVA                  is io.va true? virtual addressing (1,0)
| R2_DEBUG                 debug mode enabled? (1,0)
| R2_BLOCK                 TODO: dump current block to tmp file
| R2_SIZE                  file size
| R2_ARCH                  value of asm.arch
| RABIN2_LANG              assume this lang to demangle
| RABIN2_DEMANGLE          demangle or not
| PDB_SERVER               e pdb.server
```

**Comment by radare** [comment]
but we can change those var names later in another pr
