### PR TITLE
Fix #13633 - support nested unions

### LINKED ISSUE #13633: Nested unions are listed as struct in tuc
# Nested unions are listed as struct in tuc

### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Windows x64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21292 @ windows-x86-64 git.3.4.1-21-g29b4a5e31 commit: 29b4a5e31afa2c2b8b647ccd59463e88eaa5f11a build: 05/04/2019__ 6:21:29,29

### Steps to reproduce the behavior
```
[0x140001753]> "td union foo { int a; union bar { float b; int c; }; };"
[0x140001753]> tuc
union bar {float b; int32_t c;};
union foo {int32_t a; struct bar ;};
```
### Expected behavior

Inside foo bar is listed as struct, but it's a union

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

File: shlr/tcc/tccgen.c [hunk 1]
```diff
@@ -1155,10 +1183,10 @@ static void struct_decl(CType *type, int u) {
 							/* compact form */
 							tcc_appendf ("%s.%s.%s=%s,%d,%d\n",
 								ctype, name, varstr, b, offset, arraysize);
-#if 0
-							printf ("struct.%s.%s.type=%s\n", name, varstr, b);
-							printf ("struct.%s.%s.offset=%d\n", name, varstr, offset);
-							printf ("struct.%s.%s.array=%d\n", name, varstr, arraysize);
+#if 1
+							eprintf ("%s.%s.%s.type=%s\n", ctype, name, varstr, b);
```
Comment (radare) [inline shlr/tcc/tccgen.c]: Noisy debug messages
