### PR TITLE
Fix #7989 impl noreturn_recurse

### LINKED ISSUE #7989: noreturn functions not working on windows binaries
```
[0x00401cda]> tn
ExitProcess
```

* those are all the no-return functions for windows
* i guess this list should be longer :P
* and this ExitProcess should be catching this call sub.kernel32.ExitProcess....

image 2017-07-21 18 22 28

### PR DESCRIPTION
**Pull request by kriw**
Related to the issue #7989,
Enable to detect noreturn by looking at the first instruction of callee function.

before
radare2-96emp-before

after
radare2-96ump

### CODE REVIEW

**Comment by Maijin** [comment]
I guess this is also going to fix https://github.com/radare/radare2/issues/4929

File: libr/anal/anal.c [hunk 1]
```diff
@@ -577,6 +577,38 @@ R_API bool r_anal_noreturn_at_addr(RAnal *anal, ut64 addr) {
 	return sdb_bool_get (anal->sdb_types, K_NORET_ADDR(addr), NULL);
 }
 
+bool noreturn_recurse(RAnal *anal, ut64 addr) {
+	RAnalOp op = {0};
+	ut8 bbuf[0x10];
+	ut64 recurse_addr = UT64_MAX;
+	anal->iob.read_at (anal->iob.io, addr, bbuf, 0x10);
```
Comment (radare) [inline libr/anal/anal.c]: use sizeof (bbuf) instead of 0x10,

File: libr/anal/anal.c [hunk 2]
```diff
@@ -577,6 +577,38 @@ R_API bool r_anal_noreturn_at_addr(RAnal *anal, ut64 addr) {
 	return sdb_bool_get (anal->sdb_types, K_NORET_ADDR(addr), NULL);
 }
 
+bool noreturn_recurse(RAnal *anal, ut64 addr) {
+	RAnalOp op = {0};
+	ut8 bbuf[0x10];
```
Comment (radare) [inline libr/anal/anal.c]: initialize or check the return value of read_at()

Comment (radare) [reply libr/anal/anal.c]: "and"

**Comment by radare** [comment]
the results lgtm

File: libr/anal/anal.c (hunk 2 above)
Comment (kriw) [reply libr/anal/anal.c]: What variable should be initialized?

**Comment by radare** [comment]
Bbuf

File: libr/anal/anal.c (hunk 2 above)
Comment (radare) [reply libr/anal/anal.c]: Bbuf[0x10] = {0};
