### PR TITLE
Fix #11799 - Fix ptrace warnings

### LINKED ISSUE #11799: debug-ptrace: gcc8 warnings
```
[925/1124] Compiling C object 'libr/debug/libr@debug@@r_debug@sha/p_debug_native.c.o'.                                                                        
../libr/debug/p/debug_native.c: In function ‘r_debug_native_continue’: 
../libr/debug/p/debug_native.c:276:57: warning: passing argument 5 of ‘r_debug_ptrace’ makes pointer from integer without a cast [-Wint-conversion]
  int ret = r_debug_ptrace (dbg, PTRACE_CONT, pid, NULL, contsig);
                                                         ^~~~~~~
In file included from ../libr/debug/p/debug_native.c:4:            
../libr/include/r_debug.h:603:115: note: expected ‘r_ptrace_data_t’ {aka ‘void *’} but argument is of type ‘int’
 static inline long r_debug_ptrace(RDebug *dbg, r_ptrace_request_t request, pid_t pid, void *addr, r_ptrace_data_t data) {
                                                                                                   ~~~~~~~~~~~~~~~~^~~~
../libr/debug/p/debug_native.c:288:51: warning: passing argument 5 of ‘r_debug_ptrace’ makes pointer from integer without a cast [-Wint-conversion]
      r_debug_ptrace (dbg, PTRACE_CONT, tid, NULL, contsig);               
                                                   ^~~~~~~
In file included from ../libr/debug/p/debug_native.c:4:
../libr/include/r_debug.h:603:115: note: expected ‘r_ptrace_data_t’ {aka ‘void *’} but argument is of type ‘int’
 static inline long r_debug_ptrace(RDebug *dbg, r_ptrace_request_t request, pid_t pid, void *addr, r_ptrace_data_t data) {
                                                                                                   ~~~~~~~~~~~~~~~~^~~~
[930/1124] Compiling C object 'libr/debug/libr@debug@@r_debug@sha/p_native_linux_linux_debug.c.o'.
../libr/debug/p/native/linux/linux_debug.c: In function ‘linux_handle_signals’:
../libr/debug/p/native/linux/linux_debug.c:81:2: warning: #warning DO MORE RDEBUGREASON HERE [-Wcpp]
 #warning DO MORE RDEBUGREASON HERE
  ^~~~~~~
../libr/debug/p/native/linux/linux_debug.c: In function ‘linux_set_options’:
../libr/debug/p/native/linux/linux_debug.c:242:54: warning: passing argument 5 of ‘r_debug_ptrace’ makes pointer from integer without a cast [-Wint-conversio$
]
  if (r_debug_ptrace (dbg, PTRACE_SETOPTIONS, pid, 0, traceflags) == -1) {
                                                      ^~~~~~~~~~
In file included from ../libr/debug/p/native/linux/linux_debug.c:6:
../libr/include/r_debug.h:603:115: note: expected ‘r_ptrace_data_t’ {aka ‘void *’} but argument is of type ‘int’
 static inline long r_debug_ptrace(RDebug *dbg, r_ptrace_request_t request, pid_t pid, void *addr, r_ptrace_data_t data) {
                                                                                                   ~~~~~~~~~~~~~~~~^~~~
In file included from ../libr/include/sdb.h:1,
                 from ../libr/include/r_list.h:6,
                 from ../libr/include/r_io.h:6,
                 from ../libr/include/r_anal.h:16,
                 from ../libr/include/r_debug.h:5,
                 from ../libr/debug/p/native/linux/linux_debug.c:6:
../libr/debug/p/native/linux/linux_debug.c: In function ‘linux_reg_read’:
../libr/include/sdb/sdb.h:21:35: warning: passing argument 4 of ‘r_debug_ptrace’ makes pointer from integer without a cast [-Wint-conversion]
 #define r_offsetof(type, member) ((unsigned long) &((type*)0)->member)
                                 ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libr/debug/p/native/linux/linux_debug.c:790:6: note: in expansion of macro ‘r_offsetof’
      r_offsetof (struct user, u_debugreg[i]), 0);
      ^~~~~~~~~~
In file included from ../libr/debug/p/native/linux/linux_debug.c:6:
../libr/include/r_debug.h:603:93: note: expected ‘void *’ but argument is of type ‘long unsigned int’
 static inline long r_debug_ptrace(RDebug *dbg, r_ptrace_request_t request, pid_t pid, void *addr, r_ptrace_data_t data) {
                                                                                       ~~~~~~^~~~
In file included from ../libr/include/sdb.h:1,
                 from ../libr/include/r_list.h:6,
                 from ../libr/include/r_io.h:6,
                 from ../libr/include/r_anal.h:16,
                 from ../libr/include/r_debug.h:5,
                 from ../libr/debug/p/native/linux/linux_debug.c:6:
../libr/debug/p/native/linux/linux_debug.c: In function ‘linux_reg_write’:
../libr/include/sdb/sdb.h:21:35: warning: passing argument 4 of ‘r_debug_ptrace’ makes pointer from integer without a cast [-Wint-conversion]
 #define r_offsetof(type, member) ((unsigned long) &((type*)0)->member)
                                  ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libr/debug/p/native/linux/linux_debug.c:921:56: note: in expansion of macro ‘r_offsetof’
    if (r_debug_ptrace (dbg, PTRACE_POKEUSER, dbg->pid, r_offsetof (
                                                        ^~~~~~~~~~
In file included from ../libr/debug/p/native/linux/linux_debug.c:6:
../libr/include/r_debug.h:603:93: note: expected ‘void *’ but argument is of type ‘long unsigned int’
 static inline long r_debug_ptrace(RDebug *dbg, r_ptrace_request_t request, pid_t pid, void *addr, r_ptrace_data_t data) {
                                                                                       ~~~~~~^~~~
../libr/debug/p/native/linux/linux_debug.c:922:38: warning: passing argument 5 of ‘r_debug_ptrace’ makes pointer from integer without a cast [-Wint-conversion
]
      struct user, u_debugreg[i]), val[i])) {
                                   ~~~^~~
In file included from ../libr/debug/p/native/linux/linux_debug.c:6:
../libr/include/r_debug.h:603:115: note: expected ‘r_ptrace_data_t’ {aka ‘void *’} but argument is of type ‘long int’
 static inline long r_debug_ptrace(RDebug *dbg, r_ptrace_request_t request, pid_t pid, void *addr, r_ptrace_data_t data) {
                                                                                                   ~~~~~~~~~~~~~~~~^~~~
[943/1124] Compiling C object 'libr/core/libr@core@@r_core@sha/cfile.c.o'.
../libr/core/cfile.c: In function ‘r_core_file_reopen’:
../libr/core/cfile.c:117:9: note: #pragma message: fix debugger-concept in core
 #pragma message ("fix debugger-concept in core")
         ^~~~~~~

### PR DESCRIPTION
**Pull request by thestr4ng3r**
Fix #11799

### CODE REVIEW

File: libr/debug/p/debug_native.c [hunk 1]
```diff
@@ -273,7 +273,7 @@ static int r_debug_native_continue(RDebug *dbg, int pid, int tid, int sig) {
 		r_cons_break_push ((RConsBreak)r_debug_native_stop, dbg);
 	}
 
-	int ret = r_debug_ptrace (dbg, PTRACE_CONT, pid, NULL, contsig);
+	int ret = r_debug_ptrace (dbg, PTRACE_CONT, pid, NULL, (r_ptrace_data_t)(long)contsig);
```
Comment (radare) [inline libr/debug/p/debug_native.c]: casting thru long is scary, use size_t which is portable
