### PR TITLE
Fix #14732 - Fix out-of-bounds read

### LINKED ISSUE #14732: Segfault on panels menu
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian
| File format of the file you reverse (mandatory)      | PE, ELF etc.
| Architecture/bits of the file (mandatory)            | PPC, x86/32, x86/64 etc.
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 23236 @ linux-x86-64 git.3.6.0-308-gdb1d3ea45 commit: 7592fa52a9a0018602a4bce8cf64dcf4ee2718b3 build: 2019-07-31__18:38:41

### Expected behavior
No segfault
### Actual behavior
image

### Steps to reproduce the behavior
- `e scr.utf8=1`
- Enter panels mode `V!`
- Click on menu item
- Click on the line that separates the menu from the panels (the corner is more reliable)
- Try a few times if doesn't happen on the first time

image

image

### PR DESCRIPTION
**Pull request by GustavoLCR**
Fix #14732

### CODE REVIEW

File: libr/core/panels.c [hunk 1]
```diff
@@ -6286,11 +6286,11 @@ char *get_word_from_canvas_for_menu(RCore *core, RPanels *panels, int x, int y)
 		pos = R;
 	}
 	int i = 0;
-	while (pos && strncmp (padding, pos, strlen (padding))) {
+	while (pos > R && strncmp (padding, pos, strlen (padding))) {
 		pos--;
 		i++;
 	}
-	while (tmp && strncmp (padding, tmp, strlen (padding))) {
+	while (*tmp && strncmp (padding, tmp, strlen (padding))) {
```
Comment (radare) [inline libr/core/panels.c]: tmp can be null too
