### PR TITLE
fix #4432

### LINKED ISSUE #4432: Incorrect ESIL AND
Binary: Ubuntu 14.04 /bin/ls
Instruction: and edx, 0x200
ESIL: 512,edx,&=,0,of,=,0,cf,=,$z,zf,=,$s,sf,=,$o,pf,=
Offset: 0x40c3a7

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rdx     | 0xffffffffffffffffL -> 0x200          | -0x1 -> -0xfffffe00                   |

### PR DESCRIPTION
**Pull request by condret**

### CODE REVIEW

**Comment by sushant94** [comment]
We need to do this for almost every instruction, we should think of a way too add this into getarg directly if we can.

**Comment by condret** [comment]
i'm not sure about that atm, which is why i would like to fix it for tiny subsets first and later find a generalized version for reducing LOC

File: libr/anal/p/anal_x86_cs.c [hunk 1]
```diff
@@ -1136,7 +1136,15 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
 		{
 			char *src = getarg (&gop, 1, 0, NULL);
 			char *dst = getarg (&gop, 0, 1, "&");
+			char *p;
 			esilprintf (op, "%s,%s,$0,of,=,$0,cf,=,$z,zf,=,$s,sf,=,$o,pf,=", src, dst);
+			if ((a->bits == 64) && (p = strchr (dst, (int)','))) {
+				char *dst64;
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: why define this here when you have an orphaned variable defined of the same type above. reuse the char *p one

File: libr/anal/p/anal_x86_cs.c [hunk 2]
```diff
@@ -1136,7 +1136,15 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
 		{
 			char *src = getarg (&gop, 1, 0, NULL);
 			char *dst = getarg (&gop, 0, 1, "&");
+			char *p;
 			esilprintf (op, "%s,%s,$0,of,=,$0,cf,=,$z,zf,=,$s,sf,=,$o,pf,=", src, dst);
+			if ((a->bits == 64) && (p = strchr (dst, (int)','))) {
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: i dont think this cast really matters

File: libr/anal/p/anal_x86_cs.c [hunk 3]
```diff
@@ -1136,7 +1136,15 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
...
+				char *dst64;
+				*p = '\0';
+				if (!(dst64 = r_reg_32_to_64 (a->reg, dst)))
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: what about if () { r_strbuf_append} to avoid the memleak and make the code more readable?

File: libr/anal/p/anal_x86_cs.c (hunk 2 above)
Comment (condret) [inline libr/anal/p/anal_x86_cs.c]: well, i'm not sure, i'd just like to not produce warnings on the first try

File: libr/anal/p/anal_x86_cs.c (hunk 3 above)
Comment (condret) [inline libr/anal/p/anal_x86_cs.c]: what memleak do you mean? r_strbuf_appendf?

Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: the memleak is by placing a break before freeing the dst and src vars

File: libr/anal/p/anal_x86_cs.c (hunk 1 above)
Comment (condret) [inline libr/anal/p/anal_x86_cs.c]: because I wanted a meaningful name for the 64-bit register string. I thought p for pointer is meaningful and dst64 for 64-bit destination is meaningful

File: libr/anal/p/anal_x86_cs.c [hunk 4]
```diff
@@ -1136,7 +1136,13 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
 		{
 			char *src = getarg (&gop, 1, 0, NULL);
 			char *dst = getarg (&gop, 0, 1, "&");
+			char *p;
 			esilprintf (op, "%s,%s,$0,of,=,$0,cf,=,$z,zf,=,$s,sf,=,$o,pf,=", src, dst);
+			if ((a->bits == 64) && (p = strchr (dst, (int)','))) {
+				*p = '\0';
+				if ((p = r_reg_32_to_64 (a->reg, dst)))
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: add braces {}
