### PR TITLE
fix pd for rip varsub of AT&T syntax

### LINKED ISSUE #8521: varsub on rip based register output invalid asm for AT&T syntax
r2 output malformed assembly for the binary of the following code:
```c
static int sa = 2;
int main(void) {
	sa = 1;
	return 0;
}
```

notice the line at `0x0000061e`:

```
[0x00000510]> aa; s main; pd 5
[x] Analyze all flags starting with sym. and entry0 (aa)
            ;-- main:
/ (fcn) sym.main 21
|   sym.main ();
|              ; DATA XREF from 0x0000052d (entry0)
|           0x0000061a      55             pushq %rbp
|           0x0000061b      4889e5         movq %rsp, %rbp
|           0x0000061e      c705000a2000.  movl 0x00000628             ; obj.sa ; [0x201028:4]=2
|           0x00000628      b800000000     movl $0, %eax
|           0x0000062d      5d             popq %rbp

```

expected:

`
0x0000061e      c705000a2000.  movl $1, obj.sa
`

### PR DESCRIPTION
**Pull request by Frefreak**
fix #8521

### CODE REVIEW

File: libr/parse/p/parse_x86_pseudo.c [hunk 1]
```diff
@@ -283,8 +283,11 @@ static bool varsub (RParse *p, RAnalFunction *f, ut64 addr, int oplen, char *dat
 				*rip = 0;
 				char *pre = tstr;
 				char *pos = rip + 6;
-				char *word = strchr (tstr, ' ');
-				if (word) {
+				char *word = rip;
+				while (word > tstr && *word != ' ')
```
Comment (radare) [inline libr/parse/p/parse_x86_pseudo.c]: missing braces

**Comment by Frefreak** [comment]
added
