### PR TITLE
fix crash in oob pseudo (#7815)

### LINKED ISSUE #7815: Segmentation fault analyzing this binary
Kali x64

Video: https://asciinema.org/a/bapoiTRfinow2WetaKTqB1EH3

Binary: [tmp.zip](https://github.com/radare/radare2/files/1099922/tmp.zip)

### PR DESCRIPTION
**Pull request by lowlyw**
closes #7815

### CODE REVIEW

**Comment by lowlyw** [comment]
wtf, windows is full of shit

File: libr/parse/p/parse_x86_pseudo.c [hunk 1]
```diff
@@ -15,86 +15,88 @@
 //    0x0001f41c      eabe76de12       jmp word 0x12de:0x76be [2]
 //    0x0001f56a      ea7ed73cd3       jmp word 0xd33c:0xd77e [6]
 static int replace(int argc, const char *argv[], char *newstr) {
-	int i,j,k;
+	const int kMaxOps = 10;
+	int i,j,k,d;
```
Comment (radare) [inline libr/parse/p/parse_x86_pseudo.c]: Missing spaces

File: libr/parse/p/parse_x86_pseudo.c [hunk 2]
```diff
@@ -15,86 +15,88 @@
...
 	struct {
 		char *op;
 		char *str;
+		int args[kMaxOps];  // XXX can't use flex arrays, all unused will be 0
```
Comment (radare) [inline libr/parse/p/parse_x86_pseudo.c]: This will fail on msvc. Const int is considered varsize arrays. Use a define for kmaxops

File: libr/parse/p/parse_x86_pseudo.c [hunk 3]
```diff
@@ -107,9 +109,15 @@ static int replace(int argc, const char *argv[], char *newstr) {
...
-					if (ops[i].str[j] > '0' && ops[i].str[j] <= '9') {
-						const char *w = argv[ops[i].str[j] - '0'];
+					if (ops[i].str[j] == '#') {
+						if (ops[i].args[d] <= 0 || d >= kMaxOps) {
+							// XXX Shouldn't ever happen...
+							continue;
+						}
+						const char *w = argv[ops[i].args[d]];
+						d++;
 						if (w != NULL) {
```
Comment (radare) [inline libr/parse/p/parse_x86_pseudo.c]: !=NULL is unnecessary

File: libr/parse/p/parse_x86_pseudo.c [hunk 4]
```diff
@@ -107,9 +109,15 @@ static int replace(int argc, const char *argv[], char *newstr) {
 	for (i = 0; ops[i].op != NULL; i++) {
 		if (!strcmp (ops[i].op, argv[0])) {
 			if (newstr != NULL) {
+				d = 0;
 				for (j = k = 0; ops[i].str[j] != '\0'; j++, k++) {
-					if (ops[i].str[j] > '0' && ops[i].str[j] <= '9') {
-						const char *w = argv[ops[i].str[j] - '0'];
+					if (ops[i].str[j] == '#') {
+						if (ops[i].args[d] <= 0 || d >= kMaxOps) {
+							// XXX Shouldn't ever happen...
```
Comment (radare) [inline libr/parse/p/parse_x86_pseudo.c]: Assign ops[i.str[j to a variable instead of dereferencing 2 pointers several times
