### PR TITLE
msp430 disassembly: clean up and bug fix

### LINKED ISSUE #11000: Possible wrong dissassembly for MSP430
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Archlinux amd64 intel x86-64
| File format of the file you reverse (mandatory)      | memory dump
| Architecture/bits of the file (mandatory)            | msp430, 16 bit
| r2 -v full output, **not truncated** (mandatory)     | radare2 2.8.0 0 @ linux-x86-64 git.2.8.0 commit: HEAD build: 2018-08-08__20:56:17

### Expected behavior

Dissasemble instructions like this:

bf4f feef      mov      @r15+, -0x1002(r15)
013c           jmp      $+0x4

### Actual behavior

Dissassembles like this, interpreting the instruction to be 6 bytes instead of 4:

bf4ffeef013c   mov @r15+, 0x3c01(r15)

### Notes

The source for "Expected behavior" is https://microcorruption.com/assembler . It is possible the bug is in their code instead of here.

### PR DESCRIPTION
**Pull request by nsajko**
General cleanup of opcode selection and invalid opcode handling. Also
fixes the bug of two-operand instructions being decoded as six-bytes
long instead of four bytes long (#11000). Also fixes some out of bounds
reads.

Fixes #11000

### CODE REVIEW

File: libr/asm/arch/msp430/msp430_disas.c [hunk 1]
```diff
@@ -449,19 +432,27 @@ int msp430_decode_command(const ut8 *in, int len, struct msp430_cmd *cmd) {
 	ut8 opcode = get_twoop_opcode (instr);
```
Comment (nsajko) [inline libr/asm/arch/msp430/msp430_disas.c]: A question: does "int len" measure the length in bytes or in words (8 or 16 bits)?

**Comment by radare** [comment]
I would say bytes

File: libr/asm/arch/msp430/msp430_disas.c [hunk 2]
```diff
@@ -449,19 +432,27 @@ int msp430_decode_command(const ut8 *in, int len, struct msp430_cmd *cmd) {
...
-	case MSP430_SUB:
-	case MSP430_CMP:
-	case MSP430_DADD:
-	case MSP430_BIT:
-	case MSP430_BIC:
-	case MSP430_BIS:
-	case MSP430_XOR:
-	case MSP430_AND:
-		// XXX this conditional is wrong, but seems to be safe
+	case 0:
```
Comment (radare) [inline libr/asm/arch/msp430/msp430_disas.c]: use names instead of those magic numbers

**Comment by radare** [comment]
thanks
