### PR TITLE
fix #5940 in libr/anal/p/anal_x86_cs.c

### LINKED ISSUE #5940: Possible UB at anal_x86_cs.c due return NULL when insufficient memory
At https://github.com/radare/radare2/blob/6b56489eafc6782f0f5de34050b240ebd6abe0a7/libr/anal/p/anal_x86_cs.c#L81function getarg() which can return a NULL, the result strdup() call, or the result of calling r_str_newf(). strdup() can return NULL if insufficient memory

If we analyze r_str_newf() function here is also strdup() function, and even malloc () i.e. if we out of memory, it may well return NULL. However, getarg() function "can" return NULL and not because of lack of memory. For example here:

```
    if (!insn->detail) {
        return NULL;
    }
```

and here:

```
    if (n < 0 || n >= INSOPS) {
        return NULL;
    }
```

Returns NULL from getarg function can be either due to lack of memory, and the "usual way". There is clearly something wrong.

For example, here https://github.com/radare/radare2/blob/6b56489eafc6782f0f5de34050b240ebd6abe0a7/libr/anal/p/anal_x86_cs.c#L656-L662

```
        {
            char *src = getarg (&gop, 1, 0, NULL);
            char *dst = getarg (&gop, 0, 1, NULL);
            esilprintf (op, "%s,%s,>>>,%s", src, dst, dst);
            free (src);
            free (dst);
        }
```

esilprintf () is a wrapper around printf-like functions, and inside does not check the arguments passed to it on a NULL, if getarg() returns NULL you got UB: http://stackoverflow.com/a/11589479/6616147:

> First things first: printf is expecting a valid (i.e. non-NULL) pointer for its %s argument so passing it a NULL is officially undefined. It may print "(null)" or it may delete all files on your hard drive--either is correct behavior as far as ANSI is concerned (at least, that's what Harbison and Steele tells me.)

### PR DESCRIPTION
**Pull request by j123123**
Patched ``getarg()`` function and removed ``return strdup()``/``return r_str_newf()`` from it.
Patched ``anop_esil()`` and ``anop()`` functions to make it work with patched ``getarg()``

### CODE REVIEW

File: libr/anal/p/anal_x86_cs.c [hunk 1]
```diff
@@ -76,31 +76,35 @@ static bool is_xmm_reg(cs_x86_op op) {
...
 	char *setarg = setop ? setop : "";
 	cs_insn *insn = gop->insn;
 	csh handle = gop->handle;
 	char buf[64];
 	cs_x86_op op;
+	buf[0] = 0;
 
 	if (!insn->detail) {
-		return NULL;
+		out[0]=0;
```
Comment (j123123) [inline libr/anal/p/anal_x86_cs.c]: Maybe it's not best way to replace ``return NULL;`` ? Under normal conditions, this function can return an empty string? Like ``return strdup("");``

File: libr/anal/p/anal_x86_cs.c [hunk 2]
```diff
@@ -641,23 +650,23 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
 		// TODO: RCL Still does not work as intended
 		//  - Set flags
 		{
-			char *src = getarg (&gop, 1, 0, NULL);
-			char *dst = getarg (&gop, 0, 0, NULL);
+			char src[64];
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: define src and dst once at the begining of the function instead of doing it in aevery stackframe

File: libr/anal/p/anal_x86_cs.c [hunk 3]
```diff
@@ -1299,40 +1308,41 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
...
 		}
 		break;
 	case X86_INS_NEG:
 		{
-			char *src = getarg (&gop, 0, 0, NULL);
-			char *dst = getarg(&gop, 0, 1, NULL);
+			char src[64];
+			char dst[64];
+			getarg (&gop, 0, 0, NULL, src);
+			getarg(&gop, 0, 1, NULL, dst);
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: missing space before (

**Comment by Maijin** [comment]
screen

File: libr/anal/p/anal_x86_cs.c [hunk 4]
```diff
@@ -377,7 +387,7 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
 	case X86_INS_SETE:
 	case X86_INS_SETGE:
 		{
-			char *dst = getarg (&gop, 0, 1, NULL);
+			getarg (&gop, 0, 1, NULL, dst);
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: pass sizeof (dst)

File: libr/anal/p/anal_x86_cs.c [hunk 5]
```diff
@@ -76,31 +77,34 @@ static bool is_xmm_reg(cs_x86_op op) {
  * @param  n       Operand index
  * @param  set     if 1 it adds set (=) to the operand
  * @param  setoper Extra operation for the set (^, -, +, etc...)
- * @return         char* with the esil operand
+ * @param  out     Output
+ * @return         Void
  */
-static char *getarg(struct Getarg* gop, int n, int set, char *setop) {
+static void getarg(struct Getarg* gop, int n, int set, char *setop, char *out) {
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: add const int out_size and replace the hardcoded 64 with it

Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: uhm i think is better to have an index to point to a static char buf[4][64]; this way we can drop the char *out parameter and keep using the char *src = getarg() thing with less repeated code. The call to getarg() must specify the buffer index it will use to store the value. Tihs way we also avoid using the heap and we can return "" instead of NULL which is always nicer to print

Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: also we can use the `n` parameter as buffer selector

**Comment by radare** [comment]
Good work! thanks!
