### PR TITLE
Fix named/raw Formats in RBinField

### LINKED ISSUE #15006: Cannot find 'x' format on ihj (Inconsistent use of named/specified formats in RBinField.format)
To reproduce, open any elf binary and call `ihj`:
Bildschirmfoto vom 2019-09-10 13-36-13

This happens because here the command is created assuming `field->format` is the name of a format like it is `mach0_section` in another case, but for ELF it's just `x`:
https://github.com/radare/radare2/blob/07be18193e7d86bd6ba9a7d1a820b8a705f4e7e0/libr/core/cbin.c#L2800

### PR DESCRIPTION
**Pull request by thestr4ng3r**
Fix #15006

### CODE REVIEW

File: libr/bin/format/mach0/mach0.c [hunk 1]
```diff
@@ -3830,9 +3830,9 @@ RList *MACH0_(mach_fields)(RBinFile *bf) {
 		const char * pf_definition = cmd_to_pf_definition (lcType);
 		if (pf_definition) {
 			if (lcType != LC_BUILD_VERSION) {
-				r_list_append (ret, r_bin_field_new (addr, addr, 1, sdb_fmt ("load_command_%d_%s", n, cmd_to_string (lcType)), pf_definition, pf_definition));
+				r_list_append (ret, r_bin_field_new (addr, addr, 1, sdb_fmt ("load_command_%d_%s", n, cmd_to_string (lcType)), pf_definition, pf_definition, true));
```
Comment (radare) [inline libr/bin/format/mach0/mach0.c]: should conflict with master

**Comment by radare** [comment]
Screenshot 2019-09-16 at 18 51 49

please fix this test and resolve the conflits and im fine for merging this

**Comment by thestr4ng3r** [comment]
https://github.com/radareorg/radare2-regressions/pull/1950
