### PR TITLE
Fix #11464, reinstate Ct functionality

### LINKED ISSUE #11464: Ct causes infinite loop - parsing of the command is wrong in project
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 28, x86_64
| File format of the file you reverse (mandatory)      | ELF64
| Architecture/bits of the file (mandatory)            | x86_64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.0.0-git 19417 @ linux-x86-64 git.2.9.0-45-g1dbdabf83
commit: 1dbdabf83cbf836f586fb55a8fc683cca4ecb15c build: 2018-09-08__23:25:30

### Expected behavior
Using `Ps myproject` to save and then `r2 -p myproject`, you should be able to get to the console prompt after r2 starts up.  I know there are issues with projects at the moment, but you should at least be able to get to the console.

### Actual behavior
The prompt never appears because of the `Ct` lines in the project rc file.  The lines are not formatted properly in the rc file, nor are they parsed properly from the prompt UI (you can input the same text from the rc file into the console to get it to hang.)

### Steps to reproduce the behavior

```
$ r2 -A magic
 -- THE CAKE IS A PIE
[0x00400ad0]> Ps magic-test
[0x00400ad0]> q
$ r2 -p magic-test
```

Notice that it hangs for files with many `Ct` lines.  It may be taking a long time, because files with fewer `Ct` lines sometimes finish, but the output is all wrong.  The `Ct` lines are not being written properly to the `rc` file and are not being parsed properly in the console.

### Additional Logs, screenshots, source-code,  configuration dump, ...

The file is coming; uploading is failing at the moment...

### PR DESCRIPTION
**Pull request by Northern-Lights**
This is a fix for the `Ct` command functionality causing https://github.com/radare/radare2/pull/11465.  It ensures the proper behavior in the CLI (it's supposed to be more like `CC` than the ones handled by `cmd_meta_others`.)  It also fixes the `Ct` output lines in the `rc` project files from the `Ps` command, since they seemed to be wildly outdated or otherwise incorrect (it was `Ct size @ addr # comment` whereas the correct syntax, according to the help, is `Ct[?] [-] [comment-text] [@addr]`, identical to `CC`.)

### CODE REVIEW

**Comment by Northern-Lights** [comment]
Also referencing https://github.com/radare/radare2/issues/11469

File: libr/anal/meta.c [hunk 1]
```diff
@@ -503,6 +503,11 @@ R_API void r_meta_print(RAnal *a, RAnalMetaItem *d, int rad, bool show_full) {
 			pstr = str;
 		} else if (d->type == 's') {
 			pstr = str;
+		} else if (d->type == 't') {
+			// Sanitize (don't escape) Ct comments so we can see "char *", etc.
+			str = r_str_ndup(d->str, strlen(d->str));
```
Comment (radare) [inline libr/anal/meta.c]: Just use strdup. Add space before (

Comment (Northern-Lights) [reply libr/anal/meta.c]: Done
