### PR TITLE
fix #4422

### LINKED ISSUE #4422: Incorrect value of rax after xor eax,eax
Binary: Ubuntu 14.04 /bin/ls
Instruction: xor eax, eax
ESIL: rax,eax,^=,$z,zf,=,$p,pf,=,$s,sf,=,0,cf,=,0,of,=
Offset: 0x4026c4

| REGISTER| GDB                                   | ESIL                                  |
|---------|---------------------------------------|---------------------------------------|
| rax     | 0xb623949448d72f00L -> 0x0            | -0x49dc6b6bb728d100 -> -0x49dc6b6c00000000 |

### PR DESCRIPTION
**Pull request by condret**
this one should be better.
@radare @sushant94 rerage?

### CODE REVIEW

File: libr/anal/p/anal_x86_cs.c [hunk 1]
```diff
@@ -1013,8 +1013,17 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
 		{
 			char *src = getarg (&gop, 1, 0, NULL);
 			char *dst = getarg (&gop, 0, 1, "^");
-			esilprintf (op, "%s,%s,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=,$0,of,=",
-				src, dst);
+			char *_dst;
+			if ((a->bits == 64) && dst && (strlen (dst) == 6) && (dst[0] == 'e') && (_dst = strdup (dst))) {
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: Strlen and strdup is iterating over the string twice

File: libr/anal/p/anal_x86_cs.c [hunk 2]
```diff
@@ -1013,8 +1013,17 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
 		{
 			char *src = getarg (&gop, 1, 0, NULL);
 			char *dst = getarg (&gop, 0, 1, "^");
-			esilprintf (op, "%s,%s,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=,$0,of,=",
-				src, dst);
+			char *_dst;
```
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: Why underline? I dont think we have any statement in the syntax doc about this. Better use tmp as varname

File: libr/anal/p/anal_x86_cs.c (hunk 1 above)
Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: Too long line. Probably nesting in two lines or moving the logic intoa separate function will be more readable

File: libr/anal/p/anal_x86_cs.c (hunk 2 above)
Comment (condret) [inline libr/anal/p/anal_x86_cs.c]: i thought that _dst would be more meaningful than just tmp

File: libr/anal/p/anal_x86_cs.c (hunk 1 above)
Comment (condret) [inline libr/anal/p/anal_x86_cs.c]: so what do you want me to do about strlen + strdup?

Comment (radare) [inline libr/anal/p/anal_x86_cs.c]: Is strdup necessary for a 6 char string?

Comment (condret) [inline libr/anal/p/anal_x86_cs.c]: it is needed in a way, that because we manipulate that _dst but we cannot use dst here. (ok we could, but only if you really want it)

File: libr/anal/p/anal_x86_cs.c [hunk 3]
```diff
@@ -1015,6 +1015,12 @@ static void anop_esil (RAnal *a, RAnalOp *op, ut64 addr, const ut8 *buf, int len
 			char *dst = getarg (&gop, 0, 1, "^");
 			esilprintf (op, "%s,%s,$z,zf,=,$p,pf,=,$s,sf,=,$0,cf,=,$0,of,=",
 				src, dst);
+			if ((a->bits == 64) &&
+				dst && (strlen (dst) == 6) && (dst[0] == 'e')) {
```
Comment (sushant94) [inline libr/anal/p/anal_x86_cs.c]: Why are we checking if `strlen(dst) == 6` here?

Comment (sushant94) [inline libr/anal/p/anal_x86_cs.c]: This does not work for all cases. See: #4423 .

**Comment by sushant94** [comment]
The correct was to do it would be to see if the destination register is 32bit abd `a->bits == 32`, in which case we must reset the higher order bits too.

**Comment by condret** [comment]
i realised that later, but thanks to @crowell we now have r_reg_32_to_64 which should do the job better. Will fix that when my pr gets accepted/rejected

**Comment by radare** [comment]
👍
