### PR TITLE
Fixing aflqj

### LINKED ISSUE #13448: aflqj seems broken
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 18.04, x64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.4.0-git 21523 @ linux-x86-64 git.3.3.0-209-gb0ac77881 commit: b0ac77881e8e83c834e8b6564629b2000e709573 build: 2019-03-20__20:49:44

### Expected behavior
aflqj should return a json object of functions addresses
### Actual behavior
aflqj does not return json, but something like _7642180164218640421904042192164220112422011842201244220130422013642201424220148[]_
### Steps to reproduce the behavior 
r2 "binary"
aaa
aflqj

### PR DESCRIPTION
**Pull request by scrapbird**
Fixes #13448

### CODE REVIEW

File: libr/core/canal.c [hunk 1]
```diff
@@ -2592,7 +2592,9 @@ static int fcn_list_json(RCore *core, RList *fcns, bool quiet) {
 	pj_a (pj);
 	r_list_foreach (fcns, iter, fcn) {
 		if (quiet) {
-			r_cons_printf ("%d", fcn->addr);
+			char addrStr[11];
+			snprintf (addrStr, 11, "0x%08"PFMT64x"", fcn->addr);
+			pj_s (pj, addrStr);
```
Comment (radare) [inline libr/core/canal.c]: Address is a number. Dont make it a string and use the tight pj api for it

**Comment by scrapbird** [comment]
Sweet, will do 👍

File: libr/core/canal.c [hunk 2]
```diff
@@ -2592,7 +2592,7 @@ static int fcn_list_json(RCore *core, RList *fcns, bool quiet) {
 	pj_a (pj);
 	r_list_foreach (fcns, iter, fcn) {
 		if (quiet) {
-			r_cons_printf ("%d", fcn->addr);
+			pj_i (pj, fcn->addr);
```
Comment (radare) [inline libr/core/canal.c]: use pj_n
