### PR TITLE
fixes ood

### LINKED ISSUE #7346: ood seems to be broken
Hi,
This problem may only happens to **PIE** binary.
For the following program compiled with gcc 6.3.1
```c
int main(void)
{

	int i = -3;
	int absi = i > 0? i: -i;
	
	return 0;
}
```
When I use **ood** command r2 outputs this
```
[0x00000530]> ood
= attach 6 6
Process with PID 17787 started...
File dbg:///home/adv_zxy/tempo/a.out  reopened in read-write mode
= attach 17787 17787
Assuming filepath /home/adv_zxy/tempo/a.out
WARNING: bin_strings buffer is too big (0xffffa9d5ffc43a28). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)
WARNING: bin_strings buffer is too big (0xffffa9d5ffc43120). Use -zzz or set bin.maxstrbuf (RABIN2_MAXSTRBUF) in r2 (rabin2)
|ERROR| Invalid command '[Symbols]' (0x5b)
Enter assembler opcodes separated with ';':
:>
```
Then I just can't quit/exit r2 without kill.
If I open the binary with **-d** it behaves correctly.

I installed radare2 with `sys/install.sh`
```
$ r2 -v
radare2 1.5.0-git 14560 @ linux-x86-64 git.1.4.0-26-g6db6c6c72
commit: 6db6c6c72f0b090fcaf6373427cc445948a20beb build: 2017-04-24__16:22:32
```
I also tried radare2 1.3.0 0 from archlinux repo and it works without problem.

### PR DESCRIPTION
**Pull request by Frefreak**
fixes #7346 (ood, pie binary) and probably also related to #7461
`isrzM*` doesn't return radare commands correctly.

### CODE REVIEW

File: libr/core/cmd_open.c [hunk 1]
```diff
@@ -311,7 +311,10 @@ R_API void r_core_file_reopen_debug (RCore *core, const char *args) {
 		r_core_bin_rebase (core, new_baddr);
 		// r_core_bin_load (core, newfile, new_baddr);
 		// reload symbols with new baddr
-		r_core_cmd0 (core, ".isrzM*");
+		r_core_cmd0 (core, ".is*");
```
Comment (radare) [inline libr/core/cmd_open.c]: this fixes this specific case, but .isrzM* should work too. i can merge this if we open an issue to fix the real problem

Comment (Frefreak) [inline libr/core/cmd_open.c]: OK, opened!
