### PR TITLE
Fix multiple arrobas

### LINKED ISSUE #8857: Multiple @ suffixes sometimes do not work
Example:
photo_2017-11-20_18-14-17
First output is correct, second is wrong. The `@a:mips` is ignored

### PR DESCRIPTION
**Pull request by thestr4ng3r**
Fixes #8857.
A maximum of two @s was supported before and even then it was mostly broken. This fixes it for any number.

Also, resetting temporary evals was done in the order they were specified before, which would break if a variable was specified more than once:
```
e a=0
something @e:a=1,a=1
```
would result in a=1 afterwards.

Tests: https://github.com/radare/radare2-regressions/pull/1075

### CODE REVIEW

File: libr/core/cmd.c [hunk 1]
```diff
@@ -1504,14 +1503,19 @@ static char *parse_tmp_evals(RCore *core, const char *str) {
 		if (eq) {
 			*eq = 0;
 			const char *ov = r_config_get (core->config, kv);
-			r_strbuf_appendf (buf, "e %s=%s;", kv, ov);
+			size_t kv_len = strlen (kv);
+			size_t ov_len = strlen (ov);
+			size_t cmd_size = kv_len + ov_len + 5;
+			char *cmd = malloc (cmd_size);
```
Comment (XVilka) [inline libr/core/cmd.c]: next time please check the result of malloc.

Comment (radare) [reply libr/core/cmd.c]: No. Use r._str_newf instead of handmade malloc+snprintf
